/**
 * 纸面操作台设计提醒：设置页按档案分区，并用路线刻度明确资料、提醒、访问的操作流；每项偏好都有直接含义。
 */
import { RouteTrace, WorkspaceLayout } from "@/components/WorkspaceLayout";
import { BellRing, Check, Database, Eye, Keyboard, Save, ShieldCheck } from "lucide-react";
import { type ReactNode, useState } from "react";
import { toast } from "sonner";

export default function Settings() {
  const [workspaceName, setWorkspaceName] = useState("OPC 运营工作台");
  const [digest, setDigest] = useState(true);
  const [deadline, setDeadline] = useState(true);
  const [reducedMotion, setReducedMotion] = useState(false);
  const save = () => toast.success("偏好已保存", { description: "本次更改已应用到当前工作区。" });
  return <WorkspaceLayout><div className="px-5 pb-10 pt-8 sm:px-8 sm:pt-10 lg:px-10"><div className="mx-auto max-w-[1040px]"><section className="border-b border-[#cbc8c1] pb-8"><p className="font-mono text-[10px] tracking-[0.16em] text-[#e66b3a]">04 / 工作区设置</p><h1 className="mt-3 font-display text-[34px] leading-none tracking-[-0.04em] sm:text-[42px]">保持工具安静，<br />只留下必要的提醒。</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#667076]">这些偏好只影响当前工作区的呈现和通知节奏，不会改变团队数据。</p><RouteTrace code="PREFS / 04" label="资料 → 提醒 → 访问" className="mt-5 max-w-[620px]" /></section><section className="divide-y divide-[#d6d3cc]"><SettingsGroup index="01" title="工作区资料" icon={<Database className="h-4 w-4" />}><label className="block max-w-md"><span className="font-mono text-[10px] tracking-[0.14em] text-[#737a80]">工作区名称</span><input value={workspaceName} onChange={(event) => setWorkspaceName(event.target.value)} className="mt-2 h-10 w-full border-b border-[#aaa9a3] bg-transparent text-sm outline-none focus:border-[#e66b3a]" /></label><p className="mt-3 text-xs leading-5 text-[#747b7e]">名称会显示在小屏幕的工作区标题和导出档案上。</p></SettingsGroup><SettingsGroup index="02" title="通知节奏" icon={<BellRing className="h-4 w-4" />}><PreferenceSwitch label="每日摘要" detail="在工作日开始时汇总待决策、到期任务与容量变化。" checked={digest} onChange={setDigest} /><PreferenceSwitch label="截止前提醒" detail="在任务到期前 24 小时发送一次提醒。" checked={deadline} onChange={setDeadline} /></SettingsGroup><SettingsGroup index="03" title="阅读与操作" icon={<Eye className="h-4 w-4" />}><PreferenceSwitch label="减少动态效果" detail="关闭非必要的界面过渡，使阅读与键盘操作更直接。" checked={reducedMotion} onChange={setReducedMotion} /><div className="mt-5 flex items-center gap-3 border border-[#d6d3cc] bg-[#fbfaf7] p-3"><Keyboard className="h-4 w-4 text-[#697277]" /><p className="text-xs text-[#596369]">按 <kbd className="mx-1 border border-[#cbc8c1] bg-[#efede8] px-1.5 py-0.5 font-mono text-[10px]">⌘ K</kbd> 可随时打开工作区搜索。</p></div></SettingsGroup><SettingsGroup index="04" title="数据与访问" icon={<ShieldCheck className="h-4 w-4" />}><div className="grid gap-3 sm:grid-cols-2"><InfoBlock label="数据更新时间" value="即时同步" /><InfoBlock label="工作区权限" value="管理员" /></div><p className="mt-4 text-xs leading-5 text-[#747b7e]">成员与权限的变更将保留在工作区记录中，以便后续追溯。</p></SettingsGroup></section><div className="mt-8 flex items-center justify-between border-t border-[#cbc8c1] pt-5"><p className="hidden text-xs text-[#747b7e] sm:block">更改尚未影响其他成员的本地显示偏好。</p><button onClick={save} className="ml-auto inline-flex h-9 items-center gap-2 bg-[#20292f] px-4 text-xs font-medium text-[#f7f5f1] hover:bg-[#303b42]"><Save className="h-3.5 w-3.5" />保存更改</button></div></div></div></WorkspaceLayout>;
}
function SettingsGroup({ index, title, icon, children }: { index: string; title: string; icon: ReactNode; children: ReactNode }) { return <section className="grid gap-5 py-7 md:grid-cols-[230px_minmax(0,1fr)]"><div><p className="font-mono text-[10px] tracking-[0.15em] text-[#e66b3a]">{index} / 偏好</p><h2 className="mt-2 flex items-center gap-2 font-display text-[23px] tracking-[-0.03em]">{icon}{title}</h2></div><div>{children}</div></section>; }
function PreferenceSwitch({ label, detail, checked, onChange }: { label: string; detail: string; checked: boolean; onChange: (checked: boolean) => void }) { return <button onClick={() => onChange(!checked)} className="flex w-full items-start justify-between gap-6 border-b border-[#e1ded8] py-4 text-left last:border-b-0"><span><span className="block text-sm font-medium">{label}</span><span className="mt-1.5 block max-w-md text-xs leading-5 text-[#747b7e]">{detail}</span></span><span className={`mt-0.5 flex h-5 w-9 shrink-0 items-center p-0.5 transition-colors ${checked ? "bg-[#20292f] justify-end" : "bg-[#cbc8c1] justify-start"}`}><span className="h-4 w-4 bg-[#f7f5f1]" /></span></button>; }
function InfoBlock({ label, value }: { label: string; value: string }) { return <div className="border border-[#d6d3cc] bg-[#fbfaf7] p-4"><p className="font-mono text-[10px] text-[#7a8084]">{label}</p><p className="mt-2 flex items-center gap-2 text-sm"><Check className="h-3.5 w-3.5 text-[#627a6a]" />{value}</p></div>; }

