/**
 * 纸面操作台设计提醒：任务页像可检索的档案目录；细线、序号、路线刻度和状态色帮助扫描，不使用花哨卡片。
 */
import { RouteTrace, WorkspaceLayout } from "@/components/WorkspaceLayout";
import { type Task, type TaskPriority, type TaskState, useWorkspace } from "@/contexts/WorkspaceContext";
import { ArrowUpRight, CalendarDays, Check, Search, SlidersHorizontal, X } from "lucide-react";
import { useMemo, useState } from "react";

const statuses: ("全部" | TaskState)[] = ["全部", "待决策", "进行中", "待处理", "已完成"];

export default function Tasks() {
  const { tasks, updateTask } = useWorkspace();
  const [status, setStatus] = useState<(typeof statuses)[number]>("全部");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(tasks[0]?.id ?? null);
  const filtered = useMemo(() => tasks.filter((task) => (status === "全部" || task.state === status) && `${task.title}${task.owner}${task.project}`.toLowerCase().includes(query.toLowerCase())), [tasks, status, query]);
  const selected = tasks.find((task) => task.id === selectedId) ?? filtered[0];

  return <WorkspaceLayout><div className="px-5 pb-10 pt-8 sm:px-8 sm:pt-10 lg:px-10"><div className="mx-auto max-w-[1440px]"><section className="flex flex-col justify-between gap-6 border-b border-[#cbc8c1] pb-8 md:flex-row md:items-end"><div><p className="font-mono text-[10px] tracking-[0.16em] text-[#e66b3a]">02 / 任务队列</p><h1 className="mt-3 font-display text-[34px] leading-none tracking-[-0.04em] sm:text-[42px]">工作要有明确的下一步。</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#667076]">把注意力聚焦在等待决策、正在推进和需要重新排期的事项上。</p><RouteTrace code="QUEUE / 02" label="输入 → 负责人 → 完成记录" className="mt-5 max-w-[620px]" /></div><div className="flex items-center gap-2 text-xs text-[#737a80]"><CalendarDays className="h-4 w-4" />更新于 09:46 CST</div></section><section className="grid gap-8 pt-8 xl:grid-cols-[minmax(0,1fr)_342px]"><div className="min-w-0"><div className="flex flex-col gap-4 border-b border-[#d6d3cc] pb-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex overflow-x-auto border border-[#d6d3cc] bg-[#fbfaf7] p-0.5">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={`shrink-0 px-3 py-1.5 text-[11px] transition-colors ${status === item ? "bg-[#e8e5de] text-[#20292f]" : "text-[#737a80] hover:text-[#20292f]"}`}>{item}</button>)}</div><div className="flex items-center gap-2"><div className="flex h-9 items-center gap-2 border border-[#d6d3cc] bg-[#fbfaf7] px-3"><Search className="h-3.5 w-3.5 text-[#7c8284]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索队列" className="w-[130px] bg-transparent text-xs outline-none placeholder:text-[#9da09e]" /></div><button className="flex h-9 w-9 items-center justify-center border border-[#d6d3cc] bg-[#fbfaf7] text-[#737a80] hover:text-[#20292f]" aria-label="筛选选项"><SlidersHorizontal className="h-3.5 w-3.5" /></button></div></div><div className="mt-3 border-y border-[#d6d3cc]"><div className="hidden grid-cols-[32px_minmax(0,1fr)_100px_84px_28px] gap-4 border-b border-[#dedbd4] px-3 py-2 font-mono text-[10px] tracking-[0.1em] text-[#858a8c] sm:grid"><span>标记</span><span>任务</span><span>负责人</span><span>状态</span><span /></div>{filtered.map((task, index) => <TaskRow key={task.id} task={task} index={index} selected={selected?.id === task.id} onSelect={() => setSelectedId(task.id)} />)}{filtered.length === 0 && <div className="py-16 text-center text-sm text-[#737a80]">当前条件下没有任务。</div>}</div><p className="mt-4 font-mono text-[10px] text-[#818688]">共 {filtered.length} 项记录 · 所有更改会即时反映在工作台</p></div><TaskInspector task={selected} updateTask={updateTask} /></section></div></div></WorkspaceLayout>;
}

function TaskRow({ task, index, selected, onSelect }: { task: Task; index: number; selected: boolean; onSelect: () => void }) { return <button onClick={onSelect} className={`group grid w-full grid-cols-[26px_minmax(0,1fr)_28px] items-center gap-3 border-b border-[#e0ddd7] px-3 py-4 text-left last:border-b-0 sm:grid-cols-[32px_minmax(0,1fr)_100px_84px_28px] sm:gap-4 ${selected ? "bg-[#ebe8e2]" : "hover:bg-[#eeece7]"}`}><span className={`h-2 w-2 ${task.priority === "high" ? "bg-[#e66b3a]" : task.priority === "medium" ? "border border-[#6e7b82]" : "bg-[#c3c1bb]"}`} /><span><span className="block text-sm font-medium text-[#20292f]">{task.title}</span><span className="mt-1 block text-[11px] text-[#7a8084] sm:hidden">{task.owner} · {task.due}</span></span><span className="hidden text-xs text-[#626a70] sm:block">{task.owner}</span><span className={`hidden font-mono text-[10px] sm:block ${task.state === "待决策" ? "text-[#c95228]" : "text-[#737a80]"}`}>{task.state}</span><ArrowUpRight className="hidden h-3.5 w-3.5 text-[#9ba0a0] transition-transform duration-150 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-[#20292f] sm:block" /><span className="font-mono text-[10px] text-[#8d9294] sm:hidden">{String(index + 1).padStart(2, "0")}</span></button>; }
function TaskInspector({ task, updateTask }: { task?: Task; updateTask: (id: string, update: Partial<Pick<Task, "state" | "priority" | "owner" | "due">>) => void }) { if (!task) return <aside className="border-l border-[#d6d3cc] pl-8"><p className="text-sm text-[#737a80]">选择一项任务查看详情。</p></aside>; return <aside className="xl:border-l xl:border-[#d6d3cc] xl:pl-8"><div className="flex items-start justify-between border-b border-[#d6d3cc] pb-5"><div><p className="font-mono text-[10px] tracking-[0.16em] text-[#e66b3a]">任务档案 / {task.id.replace("t-", "")}</p><h2 className="mt-2 font-display text-[24px] leading-7 tracking-[-0.03em]">{task.title}</h2></div><button aria-label="关闭详情" className="text-[#7a8084] hover:text-[#20292f]"><X className="h-4 w-4" /></button></div><p className="border-b border-[#dedbd4] py-5 text-xs leading-6 text-[#596369]">{task.note}</p><div className="divide-y divide-[#dedbd4]"><EditableField label="状态" value={task.state} options={["待决策", "进行中", "待处理", "已完成"]} onChange={(value) => updateTask(task.id, { state: value as TaskState })} /><EditableField label="优先级" value={task.priority === "high" ? "高" : task.priority === "medium" ? "中" : "低"} options={["高", "中", "低"]} onChange={(value) => updateTask(task.id, { priority: ({ 高: "high", 中: "medium", 低: "low" }[value] as TaskPriority) })} /><EditableField label="负责人" value={task.owner} options={["林舟", "陈悦", "周晗", "吴楠", "方野"]} onChange={(value) => updateTask(task.id, { owner: value })} /><EditableField label="截止时间" value={task.due} options={["今天", "明天", "8 月 22 日", "8 月 23 日", "本周内"]} onChange={(value) => updateTask(task.id, { due: value })} /></div><button onClick={() => updateTask(task.id, { state: "已完成" })} className="mt-6 flex w-full items-center justify-center gap-2 border border-[#20292f] bg-[#20292f] py-2.5 text-xs font-medium text-[#f7f5f1] hover:bg-[#303b42]"><Check className="h-3.5 w-3.5" />标记为完成</button></aside>; }
function EditableField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="flex items-center justify-between gap-4 py-3.5"><span className="text-xs text-[#667076]">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="max-w-[155px] bg-transparent text-right font-mono text-[10px] text-[#343e44] outline-none">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
