<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {createRequestKey} from '@zhihu-koc/shared-utils'
import {cashAmount as amount,cashUnits} from './platform-earnings'
interface Http{get<T>(path:string,params?:object):Promise<T>;post<T>(path:string,data?:unknown):Promise<T>;postForm<T>(path:string,data:FormData):Promise<T>;getBlob(path:string):Promise<Blob>}
interface Scope{projectId:string;accountId:string;moduleId:string}
interface Withdrawal{id:string;userId:string;displayName:string;amount:string;status:string;receiverName:string;bankName:string;bankAccount:string;payMethod:string|null;payAccount:string|null;paymentVersion:number;paidBy:string|null;remark:string;createdAt:string;paymentReference:string;paidOn:string;proofName:string}
interface View{balance:{confirmed:string;held:string;available:string;offset:string;paid:string;processing:string}|null;withdrawals:Withdrawal[];total:number;funding:{amount:string;hash:string};canManage:boolean}
const props=defineProps<{http:Http;scope:Scope}>()
const view=ref<View|null>(null),page=ref(1),busy=ref(false),error=ref(''),notice=ref(''),applyOpen=ref(false),fundOpen=ref(false),reference=ref(''),request=ref(createRequestKey())
const applicant=reactive({amount:'',receiverName:'',payMethod:'wechat',payAccount:''})
const selected=ref<Withdrawal|null>(null),action=ref(''),reason=ref(''),proof=ref<File|null>(null),ack=ref(false),actionKey=ref(createRequestKey())
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())
const payment=reactive({reference:'',paidOn:today,remark:'',payMethod:'wechat',payAccount:''})
const history=ref<{action:string;reason:string;createdAt:string;afterJson:unknown}[]|null>(null)
let paymentBody:FormData|null=null
const labels:Record<string,string>={pending:'待线下发放',approved:'待线下发放',paid:'已线下发放',rejected:'已退回',cancelled:'已撤回'}
const methods:Record<string,string>={wechat:'微信',alipay:'支付宝',bank:'银行卡'}
async function exportPayments(){
 const rows=await props.http.get<(Withdrawal&{projectName:string})[]>('/finance/payment-sheet',props.scope)
 if(!rows.length){notice.value='目前没有待发放申请。';return}
 const cell=(v:string|undefined)=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"'
 const csv=[['申请单号','业务项目','申请人','收款人','收款方式','收款账号','金额（元）','状态'],...rows.map(r=>[r.id,r.projectName,r.displayName,r.receiverName,methods[r.payMethod??'']||r.bankName,r.payAccount||r.bankAccount,r.amount,labels[r.status]])].map(r=>r.map(cell).join(',')).join('\r\n')
 const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='待发放单_'+today+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
 notice.value='发放单已导出，实际转账后登记即可。'
}
async function load(){view.value=await props.http.get<View>('/finance',{...props.scope,page:page.value})}
async function run(fn:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=typeof e==='object'&&e&&'message'in e?String(e.message):'操作未完成，请重试'}finally{busy.value=false}}
function openApply(){applyOpen.value=true;request.value=createRequestKey()}
async function apply(){await props.http.post('/finance/withdrawals',{...props.scope,...applicant,requestKey:request.value});applyOpen.value=false;notice.value='提现申请已提交，线下发放后会更新进度。';await load()}
async function release(){if(!view.value)return;await props.http.post('/finance/funding',{...props.scope,hash:view.value.funding.hash,reference:reference.value,requestKey:actionKey.value});fundOpen.value=false;notice.value='款项已开放，相关人员可以申请提现。';await load()}
function choose(w:Withdrawal,a:string){selected.value=w;action.value=a;reason.value='';proof.value=null;payment.reference=w.paymentReference||'';payment.paidOn=w.paidOn||today;payment.remark=w.remark||'';payment.payMethod=w.payMethod||'wechat';payment.payAccount=w.payAccount||w.bankAccount||'';ack.value=false;actionKey.value=createRequestKey();paymentBody=null;history.value=null}
async function review(){if(!selected.value)return;await props.http.post('/finance/withdrawals/'+selected.value.id+'/review',{...props.scope,action:action.value,reason:reason.value});notice.value='申请已更新。';selected.value=null;await load()}
async function pay(){
 if(!selected.value||!ack.value)return
 if(!paymentBody){const form=new FormData();for(const [key,v] of Object.entries({...props.scope,...payment,requestKey:actionKey.value,acknowledged:'true'}))form.append(key,v);if(proof.value)form.append('proof',proof.value);paymentBody=form}
 try{await props.http.postForm('/finance/withdrawals/'+selected.value.id+'/pay',paymentBody)}catch(e){
  // A definite validation failure can be corrected in place. Keep the exact
  // payload only when the outcome is unknown, so a retry cannot change it.
  const status=typeof e==='object'&&e&&'status'in e?Number(e.status):0
  if(status>=400&&status<500){paymentBody=null;actionKey.value=createRequestKey()}
  throw e
 }
 selected.value=null;paymentBody=null;notice.value='已登记线下发放，系统未发起转账。';await load()
}
async function correct(){if(!selected.value)return;await props.http.post('/finance/withdrawals/'+selected.value.id+'/correct',{...props.scope,...payment,requestKey:actionKey.value,expectedVersion:selected.value.paymentVersion,action:action.value,reason:reason.value});notice.value=action.value==='void'?'已撤销发放标记，申请恢复待发放；线下款项未退回。':'已更正发放资料，原记录保留。';selected.value=null;await load()}
async function inspectHistory(w:Withdrawal){choose(w,'history');const r=await props.http.get<{list:NonNullable<typeof history.value>}>('/finance/withdrawals/'+w.id+'/history',props.scope);history.value=r.list}
async function download(w:Withdrawal){const blob=await props.http.getBlob('/finance/withdrawals/'+w.id+'/proof?'+new URLSearchParams({...props.scope}));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=w.proofName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
onMounted(()=>run(load))
</script>
<template><section class="cash-box"><div class="cash-heading"><div><h2>{{view?.canManage?'线下发放登记':'我的提现'}}</h2><p>{{view?.canManage?'实际转账后登记，系统只留痕，不发起支付。':'查看本人的可提现余额与线下发放进度。'}}</p></div><div class="cash-actions"><button v-if="view?.canManage" :disabled="busy" @click="run(exportPayments)">导出待发放单</button><button :disabled="busy" @click="run(load)">刷新</button></div></div>
<p v-if="error" class="cash-error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<template v-if="view">
<div v-if="view.balance" class="cash-metrics"><article><span>可提现</span><strong>¥{{amount(view.balance.available)}}</strong></article><article><span>待开放款项</span><strong>¥{{amount(view.balance.held)}}</strong></article><article><span>待线下发放</span><strong>¥{{amount(view.balance.processing)}}</strong></article><article><span>已线下发放</span><strong>¥{{amount(view.balance.paid)}}</strong></article></div>
<p v-if="view.balance&&cashUnits(view.balance.offset)>0n" class="cash-error">有 ¥{{amount(view.balance.offset)}} 待抵扣，请在收益明细查看更正记录。</p>
<button v-if="!view.canManage" class="cash-primary" :disabled="busy||cashUnits(view.balance?.available)<100n" @click="openApply">申请提现</button>
<p v-if="view.balance&&cashUnits(view.balance.available)<100n" class="cash-muted">账单确认且财务开放款项后，即可申请提现。</p>
<div v-if="view.canManage&&cashUnits(view.funding.amount)>0n" class="cash-attention"><span>已确认、待开放款项：<strong>¥{{amount(view.funding.amount)}}</strong></span><button :disabled="busy" @click="fundOpen=true;reference='';actionKey=createRequestKey()">登记款项可用</button></div>
<form v-if="fundOpen" class="cash-dialog" @submit.prevent="run(release)"><h3>确认款项可用</h3><p>资金备妥后，本次开放 ¥{{amount(view.funding.amount)}} 供成员申请提现。</p><label>单号或说明（选填）<input v-model="reference" maxlength="255" /></label><button class="cash-primary" :disabled="busy">确认款项可用</button><button type="button" :disabled="busy" @click="fundOpen=false">取消</button></form>
<form v-if="applyOpen" class="cash-dialog" @submit.prevent="run(apply)"><h3>申请提现</h3><label>提现金额（元）<input v-model="applicant.amount" inputmode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" required /></label><label>收款方式（选填）<select v-model="applicant.payMethod"><option value="wechat">微信</option><option value="alipay">支付宝</option><option value="bank">银行卡</option></select></label><label>收款账号（选填）<input v-model="applicant.payAccount" maxlength="128" /></label><label>收款人姓名（选填）<input v-model="applicant.receiverName" maxlength="128" /></label><button class="cash-primary" :disabled="busy">提交申请</button><button type="button" :disabled="busy" @click="applyOpen=false">取消</button></form>
<div class="cash-table"><table><thead><tr><th v-if="view.canManage">申请人</th><th>申请时间</th><th>金额（元）</th><th>收款资料</th><th>进度</th><th>操作</th></tr></thead><tbody><tr v-for="w in view.withdrawals" :key="w.id"><td v-if="view.canManage" data-label="申请人">{{w.displayName}}</td><td data-label="申请时间">{{new Date(w.createdAt).toLocaleDateString('zh-CN')}}</td><td data-label="金额（元）">{{amount(w.amount)}}</td><td data-label="收款资料"><details><summary>{{w.receiverName||w.displayName}} · {{methods[w.payMethod||'']||w.bankName||'未填写'}}</summary>{{w.payAccount||w.bankAccount||'收款账号未填写'}}</details></td><td data-label="进度">{{labels[w.status]||'处理中'}}<small>{{w.remark}}</small><small v-if="w.paidOn">发放日期：{{w.paidOn}}</small></td><td data-label="操作"><div class="cash-actions"><template v-if="view.canManage&&['pending','approved'].includes(w.status)"><button class="cash-primary" :disabled="busy" @click="choose(w,'pay')">登记已线下发放</button><button v-if="w.status==='pending'" :disabled="busy" @click="choose(w,'reject')">退回</button></template><template v-if="view.canManage&&w.status==='paid'"><button :disabled="busy" @click="choose(w,'amend')">更正发放资料</button><button :disabled="busy" @click="choose(w,'void')">撤销发放标记</button></template><button v-if="!view.canManage&&w.status==='pending'" :disabled="busy" @click="choose(w,'cancel')">撤回申请</button><button v-if="w.proofName" :disabled="busy" @click="run(()=>download(w))">付款凭证</button><button v-if="w.paymentVersion>0" :disabled="busy" @click="run(()=>inspectHistory(w))">登记与更正记录</button></div></td></tr></tbody></table></div><p v-if="!view.withdrawals.length" class="cash-empty">还没有提现申请。</p>
<form v-if="selected&&['reject','cancel'].includes(action)" class="cash-dialog" @submit.prevent="run(review)"><h3>{{action==='reject'?'退回申请':'撤回申请'}}</h3><p>{{selected.displayName}}，¥{{amount(selected.amount)}}</p><label>{{action==='reject'?'退回原因':'备注（选填）'}}<input v-model="reason" :required="action==='reject'" maxlength="500" /></label><button class="cash-primary" :disabled="busy">确认</button><button type="button" :disabled="busy" @click="selected=null">取消</button></form>
<form v-if="selected&&['pay','amend','void'].includes(action)" class="cash-dialog" @submit.prevent="run(action==='pay'?pay:correct)"><h3>{{action==='pay'?'登记已线下发放':action==='amend'?'更正发放资料':'撤销发放标记'}}</h3><p>{{selected.displayName}} · ¥{{amount(selected.amount)}}</p><p v-if="action==='void'">仅撤销系统中的发放标记，恢复待发放申请；不会退回微信或支付宝已转出的款项。</p><template v-else><label>发放日期<input type="date" v-model="payment.paidOn" :max="today" required :disabled="busy||!!paymentBody"/></label><label>发放方式（选填）<select v-model="payment.payMethod" :disabled="busy||!!paymentBody"><option value="wechat">微信</option><option value="alipay">支付宝</option><option value="bank">银行卡</option></select></label><label>收款账号（选填）<input v-model="payment.payAccount" maxlength="128" :disabled="busy||!!paymentBody"/></label><label>流水号（选填）<input v-model="payment.reference" maxlength="128" :disabled="busy||!!paymentBody"/></label><label>备注（选填）<input v-model="payment.remark" maxlength="500" :disabled="busy||!!paymentBody"/></label><label v-if="action==='pay'">凭证（选填，图片或 PDF，最大 5 MB）<input type="file" accept=".png,.jpg,.jpeg,.pdf" :disabled="busy||!!paymentBody" @change="proof=($event.target as HTMLInputElement).files?.[0]??null" /></label></template><label v-if="action!=='pay'">更正原因<input v-model="reason" required maxlength="500" /></label><label v-if="action==='pay'" class="cash-check"><input type="checkbox" v-model="ack" required />我已在线下完成转账，登记金额正确</label><button class="cash-primary" :disabled="busy||(action==='pay'&&!ack)">{{action==='pay'?'保存发放记录':'保存更正'}}</button><button type="button" :disabled="busy" @click="selected=null">取消</button></form>
<section v-if="selected&&action==='history'" class="cash-dialog"><h3>登记与更正记录</h3><p v-for="(h,i) in history" :key="i">{{new Date(h.createdAt).toLocaleString('zh-CN')}} · {{h.action==='void'?'撤销发放标记':h.action==='amend'?'更正资料':'登记发放'}} · {{h.reason||'线下发放登记'}}</p><button @click="selected=null">关闭记录</button></section>
<div v-if="view.total>25" class="cash-actions"><button :disabled="page===1||busy" @click="page--;run(load)">上一页</button><span>第 {{page}} 页</span><button :disabled="page*25>=view.total||busy" @click="page++;run(load)">下一页</button></div>
</template></section></template>
<style scoped>
.cash-box{min-width:0;padding:24px;border:1px solid var(--line,#dce2e5);border-radius:12px;background:var(--paper,#fff);margin-top:20px}.cash-heading,.cash-actions,.cash-attention{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.cash-heading h2{margin:0}.cash-heading p,.cash-muted{color:var(--ink-soft,#627078)}.cash-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(160px,100%),1fr));gap:16px;margin:20px 0}.cash-metrics article{min-width:0;overflow-wrap:anywhere;background:var(--bg,#f4f7f8);padding:18px;border-radius:10px}.cash-metrics span,.cash-metrics strong,small{display:block}.cash-metrics strong{font-size:24px;margin-top:8px}.cash-box button{border:1px solid var(--line,#dce2e5);border-radius:8px;background:var(--paper,#fff);padding:9px 14px;cursor:pointer;color:inherit}.cash-box button.cash-primary{background:#195e62;color:white;border-color:#195e62}.cash-box button:disabled{opacity:.45;cursor:not-allowed}.cash-dialog{display:flex;gap:16px;flex-wrap:wrap;margin:18px 0;padding:24px;border:2px solid #91b9bb;border-radius:12px}.cash-dialog h3,.cash-dialog p{width:100%;margin:0}.cash-dialog label{display:flex;flex:1 1 220px;gap:7px;flex-direction:column}.cash-dialog input,.cash-dialog select{box-sizing:border-box;padding:10px;border:1px solid #b8c8ca;border-radius:6px;width:100%;color:inherit;background:var(--paper,#fff)}.cash-dialog .cash-check{flex-direction:row;align-items:center;flex-basis:100%}.cash-check input{width:18px}.cash-table{overflow:auto;margin-top:20px}.cash-table table{width:100%;border-collapse:collapse;text-align:left}.cash-table td,.cash-table th{padding:12px;border-bottom:1px solid var(--line,#dce2e5);white-space:nowrap}small{color:var(--ink-soft,#627078);margin-top:6px}.cash-error{color:#a52c35}.cash-empty{padding:22px;color:var(--ink-soft,#627078);text-align:center}.cash-attention{padding:14px;background:#f3f7f5;margin-top:18px}
@media(max-width:650px){
.cash-box{padding:16px}.cash-metrics{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.cash-metrics article{padding:12px}.cash-metrics strong{font-size:20px}.cash-heading>div{min-width:0}.cash-dialog{padding:16px}.cash-dialog label{min-width:0;flex-basis:100%}.cash-table{overflow:visible}.cash-table table,.cash-table tbody{display:block}.cash-table thead{display:none}.cash-table tr{display:grid;gap:12px;padding:16px;border:1px solid var(--line,#dce2e5);border-radius:8px;margin-bottom:12px}.cash-table td{display:grid;gap:6px;min-width:0;padding:0;border:0;white-space:normal;overflow-wrap:anywhere}.cash-table td::before{content:attr(data-label);font-size:12px;color:var(--ink-soft,#627078)}.cash-table td:has(.cash-actions:empty){display:none}.cash-actions button{max-width:100%;white-space:normal}
}
</style>

