<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {createRequestKey} from '@zhihu-koc/shared-utils'
interface Http{get<T>(path:string,params?:object):Promise<T>;post<T>(path:string,data?:unknown):Promise<T>;postForm<T>(path:string,data:FormData):Promise<T>;getBlob(path:string):Promise<Blob>}
interface Scope{projectId:string;accountId:string;moduleId:string}
interface Withdrawal{id:string;userId:string;displayName:string;amount:string;status:string;receiverName:string;bankName:string;bankAccount:string;remark:string;createdAt:string;paymentReference:string;paidOn:string;proofName:string}
interface View{balance:{confirmed:string;held:string;available:string;offset:string;paid:string;processing:string}|null;withdrawals:Withdrawal[];total:number;funding:{amount:string;hash:string};canManage:boolean}
const props=defineProps<{http:Http;scope:Scope}>()
const view=ref<View|null>(null),page=ref(1),busy=ref(false),error=ref(''),notice=ref(''),applyOpen=ref(false),fundOpen=ref(false),reference=ref(''),request=ref(createRequestKey())
const applicant=reactive({amount:'',receiverName:'',bankName:'',bankAccount:''})
const selected=ref<Withdrawal|null>(null),action=ref(''),reason=ref(''),proof=ref<File|null>(null),ack=ref(false)
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())
const payment=reactive({reference:'',paidOn:today})
const labels:Record<string,string>={pending:'待财务审核',approved:'待付款',paid:'已付款',rejected:'已退回',cancelled:'已撤回'}
const amount=(v:string|undefined)=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4})
async function exportPayments(){
 const rows=await props.http.get<{id:string;projectName:string;displayName:string;receiverName:string;bankName:string;bankAccount:string;amount:string}[]>('/finance/payment-sheet',props.scope)
 if(!rows.length){notice.value='暂无审核通过、等待付款的申请。';return}
 const cell=(v:string)=>'"'+String(v).replace(/^[=+@\-\t\r]/,"'async function load()").replace(/"/g,'""')+'"'
 const csv=[['申请单号','业务项目','申请人','收款人','银行或支付渠道','收款账号','金额（元）','状态'],...rows.map(r=>[r.id,r.projectName,r.displayName,r.receiverName,r.bankName,"'"+r.bankAccount,r.amount,'待实际付款'])].map(r=>r.map(cell).join(',')).join('\r\n')
 const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='待付款单_'+today+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
 notice.value='付款单已导出。实际打款后，请逐笔登记流水和凭证。'
}
async function load(){view.value=await props.http.get<View>('/finance',{...props.scope,page:page.value})}
async function run(fn:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=e instanceof Error?e.message:'操作未完成，请重试'}finally{busy.value=false}}
function openApply(){applyOpen.value=true;request.value=createRequestKey()}
async function apply(){await props.http.post('/finance/withdrawals',{...props.scope,...applicant,requestKey:request.value});applyOpen.value=false;notice.value='提现申请已提交，财务处理后会更新进度。';await load()}
async function release(){if(!view.value)return;await props.http.post('/finance/funding',{...props.scope,hash:view.value.funding.hash,reference:reference.value});fundOpen.value=false;notice.value='已登记款项可用，相关人员可以申请提现。';await load()}
function choose(w:Withdrawal,a:string){selected.value=w;action.value=a;reason.value='';proof.value=null;payment.reference='';payment.paidOn=today;ack.value=false}
async function review(){if(!selected.value)return;await props.http.post('/finance/withdrawals/'+selected.value.id+'/review',{...props.scope,action:action.value,reason:reason.value});notice.value=action.value==='approve'?'审核通过，等待实际付款。':'申请已更新。';selected.value=null;await load()}
async function pay(){if(!selected.value||!proof.value||!ack.value)return;const form=new FormData();for(const [key,v] of Object.entries({...props.scope,...payment,acknowledged:'true'}))form.append(key,v);form.append('proof',proof.value);await props.http.postForm('/finance/withdrawals/'+selected.value.id+'/pay',form);selected.value=null;notice.value='实际付款及凭证已登记。';await load()}
async function download(w:Withdrawal){const blob=await props.http.getBlob('/finance/withdrawals/'+w.id+'/proof?'+new URLSearchParams({...props.scope}));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=w.proofName;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
onMounted(()=>run(load))
</script>
<template><section class="cash-box"><div class="cash-heading"><div><h2>{{view?.canManage?'提现与付款':'我的提现'}}</h2><p>{{view?.canManage?'审核申请，完成实际付款后登记流水和凭证。':'只展示本人的可提现余额和申请进度。'}}</p></div><div class="cash-actions"><button v-if="view?.canManage" :disabled="busy" @click="run(exportPayments)">导出待付款单</button><button :disabled="busy" @click="run(load)">刷新</button></div></div>
<p v-if="error" class="cash-error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<template v-if="view">
<div v-if="view.balance" class="cash-metrics"><article><span>可提现</span><strong>¥{{amount(view.balance.available)}}</strong></article><article><span>待开放款项</span><strong>¥{{amount(view.balance.held)}}</strong></article><article><span>提现处理中</span><strong>¥{{amount(view.balance.processing)}}</strong></article><article><span>已付款</span><strong>¥{{amount(view.balance.paid)}}</strong></article></div>
<p v-if="view.balance&&Number(view.balance.offset)>0" class="cash-error">存在 ¥{{amount(view.balance.offset)}} 的待抵扣金额，请联系财务核对来源更正。</p>
<button v-if="!view.canManage" class="cash-primary" :disabled="busy||Number(view.balance?.available??0)<0.01" @click="openApply">申请提现</button>
<p v-if="view.balance&&Number(view.balance.available)<0.01" class="cash-muted">账单确认且财务登记款项可用后，可在这里申请提现。</p>
<div v-if="view.canManage&&Number(view.funding.amount)>0" class="cash-attention"><span>已确认、待开放款项：<strong>¥{{amount(view.funding.amount)}}</strong></span><button :disabled="busy" @click="fundOpen=true;reference=''">登记到账并开放提现</button></div>
<form v-if="fundOpen" class="cash-dialog" @submit.prevent="run(release)"><h3>确认款项可用</h3><p>本次将开放 ¥{{amount(view.funding.amount)}}。请在收到款项或确认资金已经备妥后操作。</p><label>到账流水或核对说明<input v-model="reference" required maxlength="255" /></label><button class="cash-primary" :disabled="busy">确认款项可用</button><button type="button" @click="fundOpen=false">取消</button></form>
<form v-if="applyOpen" class="cash-dialog" @submit.prevent="run(apply)"><h3>申请提现</h3><label>提现金额（元）<input v-model="applicant.amount" inputmode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" required /></label><label>收款人姓名<input v-model="applicant.receiverName" required maxlength="128" /></label><label>收款银行或支付渠道<input v-model="applicant.bankName" placeholder="例如：招商银行 / 支付宝" required maxlength="128" /></label><label>收款账号<input v-model="applicant.bankAccount" required maxlength="128" /></label><button class="cash-primary" :disabled="busy">提交申请</button><button type="button" @click="applyOpen=false">取消</button></form>
<div class="cash-table"><table><thead><tr><th v-if="view.canManage">申请人</th><th>申请时间</th><th>金额（元）</th><th>收款资料</th><th>进度</th><th>操作</th></tr></thead><tbody><tr v-for="w in view.withdrawals" :key="w.id"><td v-if="view.canManage">{{w.displayName}}</td><td>{{new Date(w.createdAt).toLocaleDateString('zh-CN')}}</td><td>{{amount(w.amount)}}</td><td><details><summary>{{w.receiverName}} · {{w.bankName}}</summary>{{w.bankAccount}}</details></td><td>{{labels[w.status]||'处理中'}}<small>{{w.remark}}</small><small v-if="w.paidOn">付款日期：{{w.paidOn}}</small></td><td><div class="cash-actions"><template v-if="view.canManage&&w.status==='pending'"><button @click="choose(w,'approve')">审核通过</button><button @click="choose(w,'reject')">退回</button></template><button v-if="view.canManage&&w.status==='approved'" class="cash-primary" @click="choose(w,'pay')">登记实际付款</button><button v-if="!view.canManage&&w.status==='pending'" @click="choose(w,'cancel')">撤回申请</button><button v-if="w.proofName" :disabled="busy" @click="run(()=>download(w))">付款凭证</button></div></td></tr></tbody></table></div><p v-if="!view.withdrawals.length" class="cash-empty">暂无提现申请。</p>
<form v-if="selected&&action!=='pay'" class="cash-dialog" @submit.prevent="run(review)"><h3>{{action==='approve'?'审核通过':action==='reject'?'退回申请':'撤回申请'}}</h3><p>{{selected.receiverName}}，¥{{amount(selected.amount)}}</p><label>{{action==='reject'?'退回原因':'备注（可选）'}}<input v-model="reason" :required="action==='reject'" maxlength="500" /></label><button class="cash-primary" :disabled="busy">确认</button><button type="button" @click="selected=null">取消</button></form>
<form v-if="selected&&action==='pay'" class="cash-dialog" @submit.prevent="run(pay)"><h3>登记实际付款</h3><p>{{selected.receiverName}} · {{selected.bankName}} · {{selected.bankAccount}}</p><p>金额：¥{{amount(selected.amount)}}</p><label>付款流水号<input v-model="payment.reference" required minlength="4" maxlength="128" /></label><label>实际付款日期<input type="date" v-model="payment.paidOn" :max="today" required /></label><label>付款凭证（图片或 PDF，最大 5 MB）<input type="file" accept=".png,.jpg,.jpeg,.pdf" required @change="proof=($event.target as HTMLInputElement).files?.[0]??null" /></label><label class="cash-check"><input type="checkbox" v-model="ack" required />我已实际完成付款，并核对收款人、金额与凭证一致</label><button class="cash-primary" :disabled="busy||!ack||!proof">保存付款记录</button><button type="button" @click="selected=null">取消</button></form>
<div v-if="view.total>25" class="cash-actions"><button :disabled="page===1||busy" @click="page--;run(load)">上一页</button><span>第 {{page}} 页</span><button :disabled="page*25>=view.total||busy" @click="page++;run(load)">下一页</button></div>
</template></section></template>
<style scoped>
.cash-box{padding:24px;border:1px solid var(--line,#dce2e5);border-radius:12px;background:var(--paper,#fff);margin-top:20px}.cash-heading,.cash-actions,.cash-attention{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.cash-heading h2{margin:0}.cash-heading p,.cash-muted{color:var(--ink-soft,#627078)}.cash-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:16px;margin:20px 0}.cash-metrics article{background:var(--bg,#f4f7f8);padding:18px;border-radius:10px}.cash-metrics span,.cash-metrics strong,small{display:block}.cash-metrics strong{font-size:24px;margin-top:8px}.cash-box button{border:1px solid var(--line,#dce2e5);border-radius:8px;background:var(--paper,#fff);padding:9px 14px;cursor:pointer;color:inherit}.cash-box button.cash-primary{background:#195e62;color:white;border-color:#195e62}.cash-box button:disabled{opacity:.45;cursor:not-allowed}.cash-dialog{display:flex;gap:16px;flex-wrap:wrap;margin:18px 0;padding:24px;border:2px solid #91b9bb;border-radius:12px}.cash-dialog h3,.cash-dialog p{width:100%;margin:0}.cash-dialog label{display:flex;flex:1 1 220px;gap:7px;flex-direction:column}.cash-dialog input{box-sizing:border-box;padding:10px;border:1px solid #b8c8ca;border-radius:6px;width:100%;color:inherit;background:var(--paper,#fff)}.cash-dialog .cash-check{flex-direction:row;align-items:center;flex-basis:100%}.cash-check input{width:18px}.cash-table{overflow:auto;margin-top:20px}.cash-table table{width:100%;border-collapse:collapse;text-align:left}.cash-table td,.cash-table th{padding:12px;border-bottom:1px solid var(--line,#dce2e5);white-space:nowrap}small{color:var(--ink-soft,#627078);margin-top:6px}.cash-error{color:#a52c35}.cash-empty{padding:22px;color:var(--ink-soft,#627078);text-align:center}.cash-attention{padding:14px;background:#f3f7f5;margin-top:18px}
</style>

