export { default as WorkspaceBadge } from './WorkspaceBadge.vue'
export { default as FinanceGateBanner } from './FinanceGateBanner.vue'
export { default as AppShell } from './AppShell.vue'
export { default as RouteTrace } from './RouteTrace.vue'
export { default as StatCard } from './StatCard.vue'
export { default as LineChart } from './LineChart.vue'
export { default as BarChart } from './BarChart.vue'
export { default as DonutChart } from './DonutChart.vue'
export type { LineSeries } from './LineChart.vue'
export type { BarItem } from './BarChart.vue'
export type { DonutSlice } from './DonutChart.vue'
export type { NavItem, NavGroup, ShellAnnouncement } from './AppShell.vue'
export * from './role-tone'
export { vReveal } from './vReveal'

export {default as PlatformDashboard} from './PlatformDashboard.vue'
export {default as ModuleDirectory} from './ModuleDirectory.vue'
export {default as PublicFinance} from './PublicFinance.vue'
export {default as ProjectIntegrations} from './ProjectIntegrations.vue'
export type {CoreWorkspace} from './core-workspace'

export { default as CashWallet } from './CashWallet.vue'
export { default as StaffManager } from './StaffManager.vue'
