<script setup lang="ts">
import {ref,watch} from 'vue'
import {errorText,requestKey,type EngineContext} from '../../context'
const props=defineProps<{context:Pick<EngineContext,'http'|'scope'>;mine?:boolean;earningLineId?:string}>()
const emit=defineEmits<{changed:[]}>()
interface Item {id:string;factId:string;keyword:string;displayName:string;businessDate:string;metricType:string;detail:string;status:string;reply:string|null}
const items=ref<Item[]>([]),total=ref(0),page=ref(1),error=ref(''),notice=ref(''),busy=ref(false),detail=ref(''),raising=ref(false),reply=ref(''),target=ref<Item|null>(null)
let key=requestKey()
async function load(){const r=await props.context.http.get<{list:Item[];total:number}>(props.mine?'/objections/mine':'/objections',{...props.context.scope,page:page.value,pageSize:10});items.value=r.list;total.value=r.total}
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
async function send(){if(!detail.value.trim())return;await props.context.http.post('/objections',{...props.context.scope,earningLineId:props.earningLineId,detail:detail.value,requestKey:key});raising.value=false;detail.value='';notice.value='疑问已提交，财务回复后会显示在这里。';await load();emit('changed')}
async function respond(){if(!target.value||!reply.value.trim())return;await props.context.http.post('/objections/'+target.value.id+'/reply',{...props.context.scope,reply:reply.value,requestKey:key});target.value=null;notice.value='已回复，相关金额可以继续核对。';await load();emit('changed')}
watch(()=>[props.context.scope.projectId,props.context.scope.accountId,props.earningLineId],()=>{page.value=1;raising.value=false;target.value=null;void run(load)},{immediate:true})
</script>
<template><section class="objections"><header><h3>{{mine?'我的金额疑问':'成员金额疑问'}}</h3><button :disabled="busy" @click="run(load)">刷新疑问</button><button v-if="mine&&earningLineId&&!raising" @click="raising=true;key=requestKey();detail=''">金额有疑问</button></header><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<form v-if="raising" @submit.prevent="run(send)"><label>哪里需要核对<textarea v-model="detail" maxlength="1000" required :disabled="busy"/></label><button :disabled="busy">提交金额疑问</button><button type="button" :disabled="busy" @click="raising=false">取消</button></form>
<p v-if="!items.length&&!busy">{{mine?'还没有金额疑问。':'还没有成员提出金额疑问。'}}</p><article v-for="item in items" :key="item.id"><strong>{{item.keyword}} · {{item.businessDate}} · {{item.metricType==='activation'?'拉活':'拉新'}}</strong><span v-if="!mine">{{item.displayName}}</span><p>{{item.detail}}</p><p v-if="item.reply">财务回复：{{item.reply}}</p><span v-else>等待财务回复</span><button v-if="!mine&&item.status==='open'&&target?.id!==item.id" :disabled="busy" @click="target=item;reply='';key=requestKey()">回复疑问</button><form v-if="target?.id===item.id" @submit.prevent="run(respond)"><label>回复内容<textarea v-model="reply" maxlength="1000" required :disabled="busy"/></label><button :disabled="busy">回复并继续核对</button><button type="button" :disabled="busy" @click="target=null">取消</button></form></article><footer v-if="total>10"><button :disabled="busy||page===1" @click="page--;run(load)">上一页</button>第 {{page}} 页<button :disabled="busy||page*10>=total" @click="page++;run(load)">下一页</button></footer></section></template>
<style scoped>.objections{padding:18px;border:1px solid var(--line,#ddd);border-radius:10px;margin:18px 0;min-width:0}header,footer{display:flex;gap:12px;align-items:center;flex-wrap:wrap}h3{margin:0 auto 0 0}article{display:grid;gap:8px;padding:16px 0;border-top:1px solid var(--line,#ddd);margin-top:14px;overflow-wrap:anywhere}p{margin:8px 0}button{font:inherit;cursor:pointer;min-height:44px;border:1px solid var(--line,#ddd);border-radius:8px;padding:8px 12px;color:inherit;background:var(--paper,#fff);justify-self:start}form,label{display:grid;gap:12px;margin-top:12px}textarea{font:inherit;min-height:80px;box-sizing:border-box;width:100%;border:1px solid var(--line,#ddd);padding:10px;background:var(--paper,#fff);color:inherit}[role=alert]{color:#a02f39}</style>
