<script setup lang="ts">
import {ref} from 'vue'
import {DetailDrawer} from '@zhihu-koc/shared-components'
import {moneyValue,cashText} from '../../bill-entry'
const earningMoney=(value:string|null|undefined)=>value==null?'原表未提供':'¥'+cashText(moneyValue(value))
import {errorText,requestKey,type EngineContext} from '../../context'
const props=defineProps<{context:EngineContext}>()
const emit=defineEmits<{committed:[result:{id:string;from:string;to:string;duplicate:boolean}]}>()
interface Row {id:string;lineNumber:number;date:string;channel:string;keyword:string;orders:string|null;activations:string|null;settlement:string|null;error:string|null;status:string}
interface Preview {id:string;from:string;to:string;duplicate:boolean;previewHash:string;total:number;invalidRows:number;rows:Row[];status:string;reportType:'new_user'|'activation'}
const file=ref<File|null>(null),fileInput=ref<HTMLInputElement|null>(null),reportType=ref<'new_user'|'activation'>('new_user'),busy=ref(false),error=ref(''),open=ref(false),preview=ref<Preview|null>(null),page=ref(1),rows=ref<Row[]>([])
let previewKey=requestKey(),commitKey=requestKey()
function reset(){previewKey=requestKey();commitKey=requestKey();preview.value=null;error.value=''}
async function run(fn:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';try{await fn()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
async function inspect(){if(!file.value)return;const form=new FormData();for(const [k,v] of Object.entries({projectId:props.context.scope.projectId,accountId:props.context.scope.accountId,reportType:reportType.value,requestKey:previewKey}))form.append(k,v);form.append('file',file.value);preview.value=await props.context.http.postForm<Preview>('/workbench/import/preview',form);rows.value=preview.value.rows;page.value=1;open.value=true}
async function changePage(next:number){if(!preview.value)return;const r=await props.context.http.get<{rows:{id:string;lineNumber:number;normalizedJson:Row|string;errorText:string|null;processingStatus:string}[]}>('/imports/'+preview.value.id,{...props.context.scope,page:next,pageSize:100});rows.value=r.rows.map(r=>({...typeof r.normalizedJson==='string'?JSON.parse(r.normalizedJson):r.normalizedJson,id:r.id,lineNumber:r.lineNumber,error:r.errorText,status:r.processingStatus}));page.value=next}
async function commit(){if(!preview.value)return;await props.context.http.post('/workbench/import/'+preview.value.id+'/commit',{...props.context.scope,previewHash:preview.value.previewHash,requestKey:commitKey});open.value=false;emit('committed',preview.value)}
async function resume(batch:{id:string;fileName:string;reportKind:string}){await run(async()=>{const blob=await props.context.http.getBlob('/imports/'+batch.id+'/file?'+new URLSearchParams({projectId:props.context.scope.projectId,accountId:props.context.scope.accountId}));file.value=new File([blob],batch.fileName,{type:blob.type});reportType.value=batch.reportKind==='activation'?'activation':'new_user';reset();await inspect()})}
function chooseFile(kind?:string){if(busy.value)return;reportType.value=kind==='activation'?'activation':'new_user';file.value=null;reset();if(fileInput.value){fileInput.value.value='';fileInput.value.scrollIntoView({block:'center'});fileInput.value.click()}}
defineExpose({resume,chooseFile})
</script>
<template><section class="upload-step"><h2>上传与预览</h2><p>先检查报表内容，确认导入后再计算金额。</p><form @submit.prevent="run(inspect)"><fieldset :disabled="busy"><legend>报表类型</legend><label><input type="radio" v-model="reportType" value="new_user" @change="reset"/>拉新订单</label><label><input type="radio" v-model="reportType" value="activation" @change="reset"/>拉活</label></fieldset><label>选择报表<input ref="fileInput" type="file" accept=".xlsx,.xls,.csv" required :disabled="busy" @change="file=($event.target as HTMLInputElement).files?.[0]??null;reset()"/></label><button class="primary" :disabled="busy||!file">{{busy?'正在读取…':'预览报表'}}</button></form><p v-if="error&&!open" role="alert">{{error}} <button :disabled="busy" @click="run(inspect)">重试预览</button></p>
<DetailDrawer :open="open" title="确认报表内容" @close="!busy&&(open=false)"><template v-if="preview"><h3>{{file?.name}}</h3><p>{{preview.reportType==='activation'?'拉活':'拉新'}} · {{preview.from}} 至 {{preview.to}}</p><p>共 {{preview.total}} 行 · {{preview.invalidRows}} 行需要修正</p><p v-if="preview.duplicate">这份报表已存在，确认后不会重复计账。</p><p>关闭预览不会导入。有效行正常处理，有问题的行会保留供修正。</p><div class="preview-rows"><article v-for="r in rows" :key="r.id" :class="{invalid:!!r.error}"><strong>第 {{r.lineNumber}} 行 · {{r.keyword||'关键词未识别'}}</strong><span>{{r.date}} · {{r.channel}}</span><span v-if="preview.reportType==='activation'">拉活量 {{r.activations??'未提供'}} 个 · 补贴 {{earningMoney(r.settlement)}}</span><span v-else>订单量 {{r.orders??'未提供'}} 单</span><span v-if="r.error">{{r.error}}</span></article></div><div class="actions" v-if="preview.total>100"><button :disabled="busy||page===1" @click="run(()=>changePage(page-1))">上一页</button>第 {{page}} 页<button :disabled="busy||page*100>=preview.total" @click="run(()=>changePage(page+1))">下一页</button></div><p v-if="error" role="alert">{{error}}</p><div class="actions"><button :disabled="busy" @click="open=false">返回检查</button><button class="primary" :disabled="busy||preview.total===preview.invalidRows" @click="run(commit)">{{busy?'正在提交…':'确认导入有效行'}}</button></div></template></DetailDrawer></section></template>
<style scoped>
.upload-step{border:1px solid var(--line,#dce3e5);border-radius:12px;padding:22px;background:var(--paper,#fff);min-width:0}.upload-step h2{margin-top:0}form{display:grid;gap:18px}fieldset{display:flex;gap:24px;border:0;padding:0}fieldset label{display:flex;align-items:center;gap:8px}input[type=file]{max-width:100%;display:block;margin-top:10px}button{font:inherit;border:1px solid var(--line,#ccc);border-radius:8px;background:var(--paper,#fff);color:inherit;padding:10px 16px;cursor:pointer;min-height:44px;justify-self:start}.primary{background:var(--primary,#195e62);color:#fff}button:disabled{opacity:.5}.actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-top:18px}.preview-rows{display:grid;gap:10px;margin:18px 0}.preview-rows article{display:grid;gap:6px;padding:12px;border:1px solid var(--line,#ddd);border-radius:8px;overflow-wrap:anywhere}.invalid{background:#fff1f1}[role=alert]{color:#a02f39}
</style>
