import {beforeAll,afterAll,it,expect,vi} from 'vitest';
import {MySqlContainer,type StartedMySqlContainer} from '@testcontainers/mysql';
import mysql,{type Connection} from 'mysql2/promise';
import request from 'supertest';
import type {Express} from 'express';
import type {AuthUser} from '../../src/types';
import {runOpcMigrations} from '../../scripts/opcMigrations';
import {readFile} from 'node:fs/promises';
vi.mock('../../src/modules/zhihu/queue',async original=>({...await original<typeof import('../../src/modules/zhihu/queue')>(),enqueue:vi.fn(async()=>({id:'isolated'}))}));
let container:StartedMySqlContainer,c:Connection,pool:typeof import('../../src/db').db,app:Express;
let workbench:typeof import('../../src/modules/zhihu/attribution/workbench'),facts:typeof import('../../src/modules/zhihu/attribution/facts');
const date='2026-09-14',key=()=>crypto.randomUUID(),scope={projectId:'1',accountId:''};
const user=(sub:string,role:AuthUser['role'],duty:AuthUser['adminDuty']='all'):AuthUser=>({sub,role,adminDuty:duty,parentId:null,displayName:'人员'+sub,username:'analysis'+sub,jti:key()});
const admin=user('1','admin'),creator=user('2','creator'),ops=user('3','admin','operations'),finance=user('4','admin','finance'),leader=user('5','leader');
const headers:Record<string,Record<string,string>>={};
const q=async(sql:string,args:unknown[]=[])=> (await c.query<mysql.RowDataPacket[]>(sql,args))[0];
const file=(text:string)=>{const buffer=Buffer.from(text);return{originalname:'分析验收.csv',mimetype:'text/csv',buffer,size:buffer.length}};
let mappingId='',wordId='';
const endpoint=(id:string)=>'/api/v1/modules/zhihu/imports/'+id;
const get=(id:string,u=finance)=>request(app).get(endpoint(id)+'/analysis').set(headers[u.sub]).query(scope);
const answer=(id:string,askId:string,option:string,u=ops,selection?:unknown,requestKey=key())=>request(app).post(endpoint(id)+'/answers').set(headers[u.sub]).send({...scope,askId,option,selection,requestKey});
beforeAll(async()=>{
 container=await new MySqlContainer('mysql:8.0').withCommand(['--log-bin-trust-function-creators=1']).withDatabase('feedback_remediation_test').withUsername('test').withUserPassword('isolated').start();
 const target={host:container.getHost(),port:container.getPort(),database:container.getDatabase(),user:container.getUsername(),password:container.getUserPassword()};
 Object.assign(process.env,{DB_HOST:target.host,DB_PORT:String(target.port),DB_NAME:target.database,DB_USER:target.user,DB_PASS:target.password,OPC_MODULES:'zhihu',DEV_DEMO_AUTH:'0'});
 await runOpcMigrations(target,['zhihu']);c=await mysql.createConnection(target);
 for(const actor of [admin,creator,ops,finance,leader])await c.query('INSERT INTO users(id,username,password_hash,role,display_name,admin_duty) VALUES(?,?,?,?,?,?)',[actor.sub,actor.username,'unused',actor.role,actor.displayName,actor.adminDuty]);
 await c.query('INSERT INTO project_members(project_id,user_id) VALUES(1,2),(1,5)');
 scope.accountId=String((await q('SELECT id FROM integration_accounts LIMIT 1'))[0].id);
 await c.query("INSERT INTO channels(id,project_id,zhihu_channel_id,generation,name) VALUES(1,1,'analysis-channel',1,'分析渠道')");
 await c.query("INSERT INTO tasks(id,project_id,zhihu_task_id,name,synced_at) VALUES(1,1,'analysis-task','分析活动',NOW())");
 const resources=await import('../../src/modules/zhihu/attribution/resources');workbench=await import('../../src/modules/zhihu/attribution/workbench');facts=await import('../../src/modules/zhihu/attribution/facts');pool=(await import('../../src/db')).db;
 const mapping=await resources.createMapping(admin,scope,key(),{channelId:'1',name:'分析渠道',from:date});
 mappingId=mapping.id; const word=await resources.createKeyword(admin,scope,key(),{keyword:'分析关键词',taskId:'1',mappingId:mapping.id,landingUrl:'https://example.com/analysis',popularizeType:1});
 await c.query("UPDATE plans SET sync_status='synced',status='active',zhihu_plan_id='analysis-plan' WHERE id=?",[word.planId]);await resources.synchronizeKeywords(scope);
 wordId=word.id; const binding=await resources.distribute(admin,scope,word.id,key(),'2');await resources.changeBinding(creator,scope,binding.id,key(),{action:'activate'});
 await c.query("UPDATE zh_keyword_bindings SET activated_on=?,verification_status='passed' WHERE id=?",[date,binding.id]);
 const {ModuleRuntime}=await import('../../src/core/module-runtime'),{zhihuManifest}=await import('../../src/modules/zhihu/manifest'),{createZhihuModule}=await import('../../src/modules/zhihu/module'),{createCoreApp}=await import('../../src/core/app');
 const runtime=new ModuleRuntime([zhihuManifest]);runtime.register(createZhihuModule());app=createCoreApp(runtime);
 const {signToken}=await import('../../src/auth/jwt'),{issueRefreshSession}=await import('../../src/auth/tokenSessions');
 for(const actor of [admin,creator,ops,finance,leader]){const client='analysis-client-'+actor.sub,session=await issueRefreshSession(actor.sub,{type:'web',id:client});headers[actor.sub]={'X-Client-Id':client,Authorization:'Bearer '+await signToken({...actor,id:actor.sub,sessionId:session.familyId})};}
},90000);
afterAll(async()=>{if(pool)await pool.end();if(c)await c.end();if(container)await container.stop();});
const upload=async(day:string,channel:string,keyword:string,quantity='3')=>(await workbench.uploadReport(finance,scope,file(`日期,渠道,关键词,订单量,收益\n${day},${channel},${keyword},${quantity},987654.3210`))).id;
it('同名旧计划优先于相似词，沿用原管理员执行和成功作品且不泄漏金额',async()=>{
 const resources=await import('../../src/modules/zhihu/attribution/resources');
 await resources.createKeyword(admin,scope,key(),{keyword:'旧词甲二',taskId:'1',mappingId,landingUrl:'https://example.com/similar',popularizeType:1});
 const [created]=await c.query<mysql.ResultSetHeader>("INSERT INTO plans(project_id,zhihu_task_id,channel_id,keyword,landing_url,popularize_type,owner_id,created_by,status,sync_status,zhihu_plan_id) VALUES(1,'analysis-task','analysis-channel','旧词甲一','https://example.com/old',1,1,1,'pending','synced','old-receipt')");
 const planId=String(created.insertId);
 await c.query("INSERT INTO compositions(plan_id,owner_id,media_type,media_account,composition_type,composition_sub_type,promo_url,release_time,sync_status,zhihu_composition_id) VALUES(?,1,'KOC抖音','original',1,1,'https://example.com/original-work','2026-09-01','synced','original-receipt')",[planId]);
 const originals=await q('SELECT * FROM compositions WHERE plan_id=?',[planId]);
 const id=await upload(date,'分析渠道','旧词甲一'),raw=await q('SELECT raw_json,normalized_json FROM zh_import_rows WHERE batch_id=?',[id]);
 const run=(await get(id,ops)).body.data,ask=run.steps[2].asks[0];
 expect(ask.text).toContain('同名旧记录');expect(ask.text).toContain('人员1');expect(ask.options[0].key).toBe('legacy:'+planId);
 expect(JSON.stringify(run)).not.toMatch(/旧词甲二|987654|billableAmount|unitPrice/);
 expect((await answer(id,ask.id,ask.options[0].key,finance)).status).toBe(403);
 expect((await answer(id,ask.id,'legacy:99999')).status).toBe(409);
 const nonce=key(),saved=await answer(id,ask.id,ask.options[0].key,ops,undefined,nonce);expect(saved.status,saved.text).toBe(200);
 expect((await answer(id,ask.id,ask.options[0].key,ops,undefined,nonce)).body.data).toEqual(saved.body.data);
 const [word]=await q('SELECT k.id,b.executor_id,b.path_type,b.verification_status FROM zh_keywords k JOIN zh_keyword_bindings b ON b.id=k.current_binding_id WHERE k.plan_id=?',[planId]);
 expect(word).toMatchObject({executor_id:1,path_type:'staff_self',verification_status:'passed'});
 expect(await q('SELECT * FROM compositions WHERE plan_id=?',[planId])).toEqual(originals);
 expect(await q('SELECT raw_json,normalized_json FROM zh_import_rows WHERE batch_id=?',[id])).toEqual(raw);
 expect(await q('SELECT owner_id,created_by,zhihu_plan_id FROM plans WHERE id=?',[planId])).toEqual([{owner_id:1,created_by:1,zhihu_plan_id:'old-receipt'}]);
 const next=await upload('2026-09-15','分析渠道','旧词甲一');expect((await get(next)).body.data.steps[2].status).toBe('done');
});
it('短关键词只相同前缀不会被当作推荐候选',async()=>{
 const {nearestNames}=await import('../../src/modules/zhihu/attribution/matching');
 expect(nearestNames('旧词甲一',['旧词乙二'],x=>x)).toEqual([]);
 expect(nearestNames('旧词甲一',['旧词甲二'],x=>x)).toEqual(['旧词甲二']);
});
it('历史执行可就地补齐并自动更新，保持原归属、岗位权限与已确认账',async()=>{
 const resources=await import('../../src/modules/zhihu/attribution/resources');
 const word=await resources.createKeyword(admin,scope,key(),{keyword:'已分配历史执行',taskId:'1',mappingId,landingUrl:'https://example.com/assigned',popularizeType:1});
 await c.query("UPDATE plans SET sync_status='synced',status='active',zhihu_plan_id='assigned-receipt' WHERE id=?",[word.planId]);
 const binding=await resources.distribute(admin,scope,word.id,key(),'2');await upload(date,'分析渠道','已分配历史执行');
 const entry=()=>workbench.overview(finance,scope,{from:date,to:date}).then(v=>v.entries.find(e=>e.keywordId===word.id)!);
 expect(await entry()).toMatchObject({bindingId:binding.id,reasonCode:'BINDING_MISSING',canAssignRetro:false});
 const post=(actor:AuthUser,extra:object={},nonce=key())=>request(app).post('/api/v1/modules/zhihu/keywords/'+word.id+'/execution-history').set(headers[actor.sub]).send({...scope,bindingId:binding.id,fromDate:date,url:'https://example.com/history-evidence',description:'核对原作品与实际执行时间',requestKey:nonce,...extra});
 for(const actor of [finance,creator,leader])expect((await post(actor)).status).toBe(403);
 expect((await post(ops,{projectId:'999'})).status).toBe(403);
 expect((await post(ops,{bindingId:'999999'})).status).toBe(404);
 const nonce=key(),saved=await post(ops,{},nonce);expect(saved.status,saved.text).toBe(200);
 expect((await post(ops,{},nonce)).body.data).toEqual(saved.body.data);
 expect(await entry()).toMatchObject({amount:'24.0000',reasonCode:'WORK_UNVERIFIED',ready:false});
 expect(await q('SELECT executor_id FROM zh_keyword_bindings WHERE id=?',[binding.id])).toEqual([{executor_id:2}]);
 const jobs=await request(app).get('/api/v1/modules/zhihu/evidence/historical-tasks').set(headers[ops.sub]).query({...scope,keywordId:word.id,page:1,pageSize:25});
 expect(jobs.body.data.list).toHaveLength(1);expect(jobs.body.data.list[0].canReview).toBe(true);
 const verified=await request(app).post('/api/v1/modules/zhihu/evidence/'+saved.body.data.evidenceId+'/review').set(headers[ops.sub]).send({...scope,accept:true,reason:'已核对原作品',requestKey:key()});expect(verified.status,verified.text).toBe(200);
 expect(await entry()).toMatchObject({ready:true,reasonCode:''});
 const before=await workbench.overview(finance,scope,{from:date,to:date});await workbench.confirmBills(finance,scope,{from:date,to:date},key(),before.reviewHash);
 const confirmed=await q("SELECT * FROM zh_statement_entries WHERE status='confirmed'");
 expect((await post(ops)).status).toBe(409);expect(await q("SELECT * FROM zh_statement_entries WHERE status='confirmed'")).toEqual(confirmed);
});
it('SQL字符串零转换为真正的false，代理待办不会变成指定执行人',async()=>{
 process.env.ZHIHU_ACTIVATION_ENABLED='true';
 await workbench.uploadReport(finance,scope,file(`日期,渠道,关键词,拉活量,代理名称\n${date},分析渠道,分析关键词,3,待登记代理`),'activation');
 const result=await request(app).get('/api/v1/modules/zhihu/exceptions').set(headers[admin.sub]).query({...scope,status:'open',search:'分析关键词'});
 const agency=result.body.data.list.find((i:{reasonCode:string})=>i.reasonCode==='AGENCY_NOT_CONFIGURED');
 expect(agency).toBeTruthy();expect(agency.canAssignRetro).toBe(false);expect(agency.next).toContain('代理名称');
});
