import {beforeAll,afterAll,it,expect,vi} from 'vitest';
import {MySqlContainer,type StartedMySqlContainer} from '@testcontainers/mysql';
import mysql,{type Connection} from 'mysql2/promise';
import request from 'supertest';
import type {Express} from 'express';
import type {AuthUser} from '../../src/types';
import {runOpcMigrations} from '../../scripts/opcMigrations';
import {readFile} from 'node:fs/promises';
vi.mock('../../src/modules/zhihu/queue',async original=>({...await original<typeof import('../../src/modules/zhihu/queue')>(),enqueue:vi.fn(async()=>({id:'isolated'}))}));
let container:StartedMySqlContainer,c:Connection,pool:typeof import('../../src/db').db,app:Express;
let workbench:typeof import('../../src/modules/zhihu/attribution/workbench'),facts:typeof import('../../src/modules/zhihu/attribution/facts');
const date='2026-09-14',key=()=>crypto.randomUUID(),scope={projectId:'1',accountId:''};
const user=(sub:string,role:AuthUser['role'],duty:AuthUser['adminDuty']='all'):AuthUser=>({sub,role,adminDuty:duty,parentId:null,displayName:'人员'+sub,username:'analysis'+sub,jti:key()});
const admin=user('1','admin'),creator=user('2','creator'),ops=user('3','admin','operations'),finance=user('4','admin','finance'),leader=user('5','leader');
const headers:Record<string,Record<string,string>>={};
const q=async(sql:string,args:unknown[]=[])=> (await c.query<mysql.RowDataPacket[]>(sql,args))[0];
const file=(text:string)=>{const buffer=Buffer.from(text);return{originalname:'分析验收.csv',mimetype:'text/csv',buffer,size:buffer.length}};
let mappingId='',wordId='';
const endpoint=(id:string)=>'/api/v1/modules/zhihu/imports/'+id;
const get=(id:string,u=finance)=>request(app).get(endpoint(id)+'/analysis').set(headers[u.sub]).query(scope);
const answer=(id:string,askId:string,option:string,u=ops,selection?:unknown,requestKey=key())=>request(app).post(endpoint(id)+'/answers').set(headers[u.sub]).send({...scope,askId,option,selection,requestKey});
beforeAll(async()=>{
 container=await new MySqlContainer('mysql:8.0').withCommand(['--log-bin-trust-function-creators=1']).withDatabase('import_history_test').withUsername('test').withUserPassword('isolated').start();
 const target={host:container.getHost(),port:container.getPort(),database:container.getDatabase(),user:container.getUsername(),password:container.getUserPassword()};
 Object.assign(process.env,{DB_HOST:target.host,DB_PORT:String(target.port),DB_NAME:target.database,DB_USER:target.user,DB_PASS:target.password,OPC_MODULES:'zhihu',DEV_DEMO_AUTH:'0'});
 await runOpcMigrations(target,['zhihu']);c=await mysql.createConnection(target);
 for(const actor of [admin,creator,ops,finance,leader])await c.query('INSERT INTO users(id,username,password_hash,role,display_name,admin_duty) VALUES(?,?,?,?,?,?)',[actor.sub,actor.username,'unused',actor.role,actor.displayName,actor.adminDuty]);
 await c.query('INSERT INTO project_members(project_id,user_id) VALUES(1,2),(1,5)');
 scope.accountId=String((await q('SELECT id FROM integration_accounts LIMIT 1'))[0].id);
 await c.query("INSERT INTO channels(id,project_id,zhihu_channel_id,generation,name) VALUES(1,1,'analysis-channel',1,'分析渠道')");
 await c.query("INSERT INTO tasks(id,project_id,zhihu_task_id,name,synced_at) VALUES(1,1,'analysis-task','分析活动',NOW())");
 const resources=await import('../../src/modules/zhihu/attribution/resources');workbench=await import('../../src/modules/zhihu/attribution/workbench');facts=await import('../../src/modules/zhihu/attribution/facts');pool=(await import('../../src/db')).db;
 const mapping=await resources.createMapping(admin,scope,key(),{channelId:'1',name:'分析渠道',from:date});
 mappingId=mapping.id; const word=await resources.createKeyword(admin,scope,key(),{keyword:'分析关键词',taskId:'1',mappingId:mapping.id,landingUrl:'https://example.com/analysis',popularizeType:1});
 await c.query("UPDATE plans SET sync_status='synced',status='active',zhihu_plan_id='analysis-plan' WHERE id=?",[word.planId]);await resources.synchronizeKeywords(scope);
 wordId=word.id; const binding=await resources.distribute(admin,scope,word.id,key(),'2');await resources.changeBinding(creator,scope,binding.id,key(),{action:'activate'});
 await c.query("UPDATE zh_keyword_bindings SET activated_on=?,verification_status='passed' WHERE id=?",[date,binding.id]);
 const {ModuleRuntime}=await import('../../src/core/module-runtime'),{zhihuManifest}=await import('../../src/modules/zhihu/manifest'),{createZhihuModule}=await import('../../src/modules/zhihu/module'),{createCoreApp}=await import('../../src/core/app');
 const runtime=new ModuleRuntime([zhihuManifest]);runtime.register(createZhihuModule());app=createCoreApp(runtime);
 const {signToken}=await import('../../src/auth/jwt'),{issueRefreshSession}=await import('../../src/auth/tokenSessions');
 for(const actor of [admin,creator,ops,finance,leader]){const client='analysis-client-'+actor.sub,session=await issueRefreshSession(actor.sub,{type:'web',id:client});headers[actor.sub]={'X-Client-Id':client,Authorization:'Bearer '+await signToken({...actor,id:actor.sub,sessionId:session.familyId})};}
},90000);
afterAll(async()=>{if(pool)await pool.end();if(c)await c.end();if(container)await container.stop();});
const upload=async(day:string,channel:string,keyword:string,quantity='3')=>(await workbench.uploadReport(finance,scope,file(`日期,渠道,关键词,订单量,收益\n${day},${channel},${keyword},${quantity},987654.3210`))).id;
const action=(id:string,path:string,data:object={},actor=finance)=>request(app).post(endpoint(id)+'/'+path).set(headers[actor.sub]).send({...scope,requestKey:key(),...data});
const history=(archived=false)=>request(app).get('/api/v1/modules/zhihu/imports').set(headers[finance.sub]).query({...scope,archived:String(archived),page:1,pageSize:100});
it('清理与恢复仅影响列表，保留原报表、待办、已确认账单并拒绝越权',async()=>{
 const id=await upload(date,'分析渠道','分析关键词');
 const before=await workbench.overview(finance,scope,{from:date,to:date});await workbench.confirmBills(finance,scope,{from:date,to:date},key(),before.reviewHash);
 const snapshot=async()=>({rows:await q('SELECT * FROM zh_import_rows WHERE batch_id=?',[id]),facts:await q('SELECT * FROM zh_metric_facts'),bills:await q("SELECT * FROM zh_statement_entries WHERE status='confirmed'"),earnings:await q('SELECT * FROM opc_income_entries'),exceptions:await q('SELECT * FROM zh_exceptions')});
 const original=await snapshot();expect(original.bills.length).toBeGreaterThan(0);
 for(const actor of [ops,creator,leader])expect((await action(id,'archive',{archived:true},actor)).status).toBe(403);
 expect((await action(id,'archive',{archived:true,projectId:'999'})).status).toBe(403);
 expect((await action('999999','archive',{archived:true})).status).toBe(404);
 const requestKey=key(),saved=await action(id,'archive',{archived:true,requestKey});expect(saved.status,saved.text).toBe(200);
 expect((await action(id,'archive',{archived:true,requestKey})).body.data).toEqual(saved.body.data);
 expect((await history()).body.data.list.map((b: {id:string})=>b.id)).not.toContain(id);
 expect((await history(true)).body.data.list.map((b: {id:string})=>b.id)).toContain(id);
 expect((await request(app).get(endpoint(id)).set(headers[finance.sub]).query(scope)).body.data.archivedAt).toBeTruthy();
 expect((await get(id)).status).toBe(200);expect(await snapshot()).toEqual(original);
 expect((await action(id,'archive',{archived:false})).status).toBe(200);
 expect((await history()).body.data.list.map((b: {id:string})=>b.id)).toContain(id);
 expect((await history(true)).body.data.list.map((b: {id:string})=>b.id)).not.toContain(id);
 expect((await action(id,'reanalyze')).status).toBe(202);expect(await snapshot()).toEqual(original);
});
it('重新分析重试未匹配记录，原文件和人工决定保留，同文件重传不重复计账',async()=>{
 const id=await upload('2026-09-15','分析渠道','后登记关键词');
 expect((await q('SELECT processing_status FROM zh_import_rows WHERE batch_id=?',[id]))[0].processing_status).toBe('exception');
 // Simulate the catalog becoming available between two analyses, without calling an automatic-repair path.
 await c.query("UPDATE zh_keywords SET keyword='后登记关键词' WHERE id=?",[wordId]);
 for(const actor of [ops,creator,leader])expect((await action(id,'reanalyze',{},actor)).status).toBe(403);
 expect((await action(id,'reanalyze',{projectId:'999'})).status).toBe(403);
 expect((await action('999999','reanalyze')).status).toBe(404);
 const raw=await q('SELECT raw_json,normalized_json FROM zh_import_rows WHERE batch_id=?',[id]);
 const requestKey=key();expect((await action(id,'reanalyze',{requestKey})).status).toBe(202);
 expect((await q('SELECT processing_status FROM zh_import_rows WHERE batch_id=?',[id]))[0].processing_status).toBe('processed');
 const factsBefore=await q('SELECT * FROM zh_metric_facts'),revisions=await q('SELECT * FROM zh_metric_revisions');
 expect((await action(id,'reanalyze',{requestKey})).status).toBe(202);
 await action(id,'archive',{archived:true});
 const duplicate=await upload('2026-09-15','分析渠道','后登记关键词');expect(duplicate).toBe(id);
 expect((await history()).body.data.list.map((b: {id:string})=>b.id)).toContain(id);
 expect(await q('SELECT * FROM zh_metric_facts')).toEqual(factsBefore);expect(await q('SELECT * FROM zh_metric_revisions')).toEqual(revisions);
 expect(await q('SELECT raw_json,normalized_json FROM zh_import_rows WHERE batch_id=?',[id])).toEqual(raw);
 await c.query("UPDATE zh_keywords SET keyword='分析关键词' WHERE id=?",[wordId]);
});
it('重传修正文件仍需核对新旧数字，重新分析旧报表不会重新提出已处理的更正',async()=>{
 const older=await upload('2026-09-16','分析渠道','分析关键词','3');
 const newer=await upload('2026-09-16','分析渠道','分析关键词','5');
 const ask=(await get(newer)).body.data.steps[5].asks[0];expect(ask).toBeTruthy();
 const option=ask.options.find((o:{key:string})=>o.key==='new');expect(option).toBeTruthy();
 const accepted=await answer(newer,ask.id,option.key,finance);expect(accepted.status,accepted.text).toBe(200);
 const before=await q('SELECT * FROM zh_metric_revisions'),choices=await q('SELECT * FROM opc_analysis_answers');
 expect((await action(older,'reanalyze')).status).toBe(202);expect((await action(newer,'reanalyze')).status).toBe(202);
 expect(await q('SELECT * FROM zh_metric_revisions')).toEqual(before);expect(await q('SELECT * FROM opc_analysis_answers')).toEqual(choices);
});
it('尚在读取的报表不能被清理，其他记录的已清理状态不串到详情',async()=>{
 const id=await upload('2026-09-17','分析渠道','分析关键词');
 await c.query("UPDATE zh_import_rows SET processing_status='pending' WHERE batch_id=?",[id]);
 expect((await action(id,'archive',{archived:true})).status).toBe(409);
 await facts.processBatch(finance,scope,id);expect((await action(id,'archive',{archived:true})).status).toBe(200);
 const fresh=await upload('2026-09-18','分析渠道','分析关键词');
 expect((await request(app).get(endpoint(fresh)).set(headers[finance.sub]).query(scope)).body.data.archivedAt).toBeNull();
});
it('拉活重传保持类型隔离，重复运行清理记录迁移保留原账和清理状态',async()=>{
 process.env.ZHIHU_ACTIVATION_ENABLED='true';
 const source=file(`日期,渠道,关键词,拉活量\n${date},分析渠道,分析关键词,7`);
 const imported=await workbench.uploadReport(finance,scope,source,'activation');
 const before=await q("SELECT * FROM zh_metric_facts WHERE metric_type='new_user'"),confirmed=await q("SELECT * FROM zh_statement_entries WHERE status='confirmed'");
 expect((await action(imported.id,'reanalyze')).status).toBe(202);
 const repeat=await workbench.uploadReport(finance,scope,source,'activation');expect(repeat).toMatchObject({id:imported.id,duplicate:true});
 expect((await q("SELECT * FROM zh_metric_facts WHERE metric_type='activation'")).length).toBe(1);
 expect(await q("SELECT * FROM zh_metric_facts WHERE metric_type='new_user'")).toEqual(before);
 expect((await action(imported.id,'archive',{archived:true})).status).toBe(200);
 const archives=await q('SELECT * FROM zh_import_history_archive'),rows=await q('SELECT * FROM zh_import_rows');
 const migration=await readFile('schema/zhihu/037_import_history.sql','utf8');await c.query(migration);await c.query(migration);
 expect(await q('SELECT * FROM zh_import_history_archive')).toEqual(archives);expect(await q('SELECT * FROM zh_import_rows')).toEqual(rows);
 expect(await q("SELECT * FROM zh_statement_entries WHERE status='confirmed'")).toEqual(confirmed);
});
