<script setup lang="ts">
import {reactive,ref,watch} from 'vue'
import {errorText,requestKey,type EngineContext} from './context'
const props=defineProps<{context:EngineContext}>(),emit=defineEmits<{refresh:[];projects:[]}>()
const form=reactive({channelId:props.context.options.channels[0]?.id||'',name:'',from:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())}),busy=ref(false),error=ref(''),notice=ref('')
watch(()=>props.context.options.channels,channels=>{if(!form.channelId)form.channelId=channels[0]?.id||''})
const fmtTime=(value?:string|null)=>value?new Date(value).toLocaleString('zh-CN'):'—'
async function save(){busy.value=true;error.value='';try{await props.context.http.post('/channel-mappings',{...props.context.scope,...form,requestKey:requestKey()});notice.value='报表渠道名称已保存。';emit('refresh')}catch(e){error.value=errorText(e)}finally{busy.value=false}}
</script>
<template><section class="work-card"><div class="section-heading"><div><h2>渠道与任务</h2><p>先配置项目接入，再将报表中的渠道名称与实际渠道对应。</p></div><div class="engine-actions"><button @click="emit('refresh')">刷新资料</button><button @click="emit('projects')">管理项目接入</button></div></div><p v-if="error" class="engine-error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><div class="engine-table"><table><thead><tr><th>渠道</th><th>知乎渠道号</th><th>报表中使用的名称</th><th>同步时间</th></tr></thead><tbody><tr v-for="c in context.options.channels" :key="c.id"><td>{{c.name}}</td><td>{{c.zhihuChannelId}}</td><td>{{context.options.mappings.filter(m=>m.channelId===c.id).map(m=>m.channelName).join('、')||'尚未设置'}}</td><td>{{fmtTime(c.syncedAt)}}</td></tr></tbody></table></div><p v-if="!context.options.channels.length" class="empty-state">还没有渠道资料，请先完成项目的知乎接入。</p><details v-if="context.options.channels.length"><summary>添加报表渠道名称</summary><form @submit.prevent="save"><label>对应渠道<select v-model="form.channelId" required><option v-for="c in context.options.channels" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>报表中的渠道名称<input v-model="form.name" required maxlength="255" /></label><label>开始使用日期<input v-model="form.from" type="date" required /></label><button class="primary" :disabled="busy">保存</button></form></details><h2 style="margin-top:24px">推广任务</h2><p>与任务列表共用知乎同步资料。知乎任务单价仅供参考，成员结算以“定价规则”为准。</p><div class="engine-table" v-if="context.options.tasks.length"><table><thead><tr><th>任务</th><th>知乎任务号</th><th>知乎单价</th><th>结算方式</th><th>状态</th><th>有效期</th><th>同步时间</th></tr></thead><tbody><tr v-for="t in context.options.tasks" :key="t.id"><td>{{t.name}}</td><td>{{t.zhihuTaskId}}</td><td>{{t.unitPrice==null?'未提供':'¥'+t.unitPrice}}</td><td>{{t.settleType||'未提供'}}</td><td>{{t.status||'未知'}}</td><td>{{fmtTime(t.startTime)}} 至 {{t.endTime?fmtTime(t.endTime):'未提供结束时间'}}</td><td>{{fmtTime(t.syncedAt)}}</td></tr></tbody></table></div><p v-if="!context.options.tasks.length">尚未接入推广任务。</p></section></template>

