<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {errorText,requestKey,type EngineContext} from './context'
const props=defineProps<{context:EngineContext}>()
interface Issue{id:string;reasonCode:string;status:string;revisionId:string|null;expectedRevisionId:string|null;normalizedJson:{keyword:string;orders:string}|null}
const list=ref<Issue[]>([]),page=ref(1),busy=ref(false),error=ref(''),selected=ref<Issue|null>(null),reason=ref('')
const finance=props.context.adminDuty==='finance',operations=props.context.adminDuty==='operations'
const canHandle=(i:Issue)=>i.revisionId?!operations:!finance
const messages:Record<string,string>={CHANNEL_UNMAPPED:'渠道名称未对应，请补充渠道设置',KEYWORD_UNKNOWN:'找不到这个关键词，请核对报表或创建关键词',PROJECT_MISMATCH:'报表与当前项目不一致',BINDING_MISSING:'关键词尚未分配或使用',PERIOD_AMBIGUOUS:'报表日期早于关键词开始使用日期',PRICE_MISSING:'尚未设置对应成员的单价',SOURCE_REVISION_PENDING:'知乎更正了原来的数据，请核对新金额',RISK_REVIEW_REQUIRED:'知乎标记了风险，请联系渠道方核实',REPORT_INCOMPLETE:'还缺订单数据，请上传完整报表',LEGACY_SHARED:'历史关键词多人共用，需要核对归属'}
async function load(){try{list.value=(await props.context.http.get<{list:Issue[]}>('/exceptions',{...props.context.scope,page:page.value,pageSize:25})).list}catch(e){error.value=errorText(e)}}
async function resolve(accept:boolean){if(!selected.value)return;busy.value=true;error.value='';try{const i=selected.value;await props.context.http.post(i.revisionId?'/metric-revisions/'+i.revisionId+'/resolve':'/exceptions/'+i.id+'/retry',{...props.context.scope,requestKey:requestKey(),accept,expectedRevisionId:i.expectedRevisionId,reason:reason.value});selected.value=null;await load()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
onMounted(load)
</script>
<template><section class="work-card"><div class="section-heading"><div><h2>数据待办</h2><p>只处理无法自动确定的项目。补齐资料后重新计算即可。</p></div><button @click="load">刷新</button></div><p class="engine-error" v-if="error" role="alert">{{error}}</p><div class="engine-table"><table><thead><tr><th>关键词</th><th>需要处理什么</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="i in list" :key="i.id"><td>{{i.normalizedJson?.keyword||'报表记录'}}</td><td class="cell-note">{{messages[i.reasonCode]||'需要核对来源数据'}}</td><td>{{i.status==='open'?'待处理':'已处理'}}</td><td><button v-if="i.status==='open'&&i.reasonCode!=='RISK_REVIEW_REQUIRED'&&canHandle(i)" @click="selected=i;reason=''">{{i.revisionId?'核对更正':'资料已补齐，重新计算'}}</button><span v-else-if="i.status==='open'">{{i.revisionId?'请财务核对更正':'请运营补齐资料'}}</span></td></tr></tbody></table></div><p class="empty-state" v-if="!list.length">暂无数据待办。</p><form v-if="selected" class="confirm-box" @submit.prevent="resolve(true)"><h2>{{selected.normalizedJson?.keyword}}</h2><p v-if="selected.revisionId">更正后的订单量：{{selected.normalizedJson?.orders??'未提供'}}。接受后，系统会重新计算金额并保留更正记录。</p><label>处理说明<input v-model="reason" required maxlength="500" /></label><button class="primary" :disabled="busy">{{selected.revisionId?'接受更正':'重新计算'}}</button><button v-if="selected.revisionId" type="button" :disabled="!reason||busy" @click="resolve(false)">不接受更正</button><button type="button" @click="selected=null">取消</button></form><div class="engine-actions" v-if="page>1||list.length===25"><button :disabled="page===1" @click="page--;load()">上一页</button><button :disabled="list.length<25" @click="page++;load()">下一页</button></div></section></template>

