<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue'
import {errorText,requestKey,type EngineContext} from './context'
const props=defineProps<{context:EngineContext}>(),emit=defineEmits<{refresh:[]}>()
interface Word{id:string;keyword:string;taskId:string;lifecycleStatus:string;syncStatus:string;syncError:string|null;priorityEnded:number;bindingId:string|null;executorId:string|null;leaderId:string|null;releaseStatus:string;usedEverAt:string|null;verificationStatus:string;executorName?:string}
const list=ref<Word[]>([]),total=ref(0),page=ref(1),search=ref(''),busy=ref(false),error=ref(''),notice=ref(''),createOpen=ref(false)
const selected=ref<Word|null>(null),action=ref(''),target=ref(''),reason=ref(''),work=reactive({url:'',description:''}),operationKey=ref(requestKey())
const form=reactive({keyword:'',taskId:props.context.options.tasks[0]?.id||'',mappingId:props.context.options.mappings[0]?.id||'',landingUrl:'',popularizeType:1})
const prices=ref<{taskId:string;payeeId:string;price:string;priceStatus:string;startDay:string;endDay:string|null}[]>([])
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())
const admin=computed(()=>props.context.role==='admin')
const status:Record<string,string>={pending:'创建处理中',available:'可以领取',reserved:'等待分发',assigned:'待提交作品',active:'使用中',retired:'已停用'}
const members=computed(()=>props.context.options.users.filter(u=>action.value==='distribute'?u.role==='leader'||u.role==='creator':u.id===selected.value?.leaderId||u.role==='creator'&&u.parentId===selected.value?.leaderId))
function price(w:Word){const p=prices.value.find(p=>p.taskId===w.taskId&&p.payeeId===props.context.userId&&p.priceStatus==='published'&&p.startDay<=today&&(!p.endDay||p.endDay>today));return p?'¥'+Number(p.price)+' / 单':'等待设置单价'}
async function load(){const r=await props.context.http.get<{list:Word[];total:number}>('/keywords',{...props.context.scope,page:page.value,pageSize:25,search:search.value});list.value=r.list;total.value=r.total}
async function run(fn:()=>Promise<unknown>){if(busy.value)return;busy.value=true;error.value='';try{await fn();await load()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
function post(path:string,data:object={},key:string=requestKey()){return props.context.http.post(path,{...props.context.scope,...data,requestKey:key})}
function choose(w:Word,a:string){selected.value=w;action.value=a;target.value='';reason.value='';work.url='';work.description='';operationKey.value=requestKey()}
async function perform(){const w=selected.value;if(!w)return;
 if(action.value==='work'){if(!w.usedEverAt)await post('/bindings/'+w.bindingId+'/activate',{},operationKey.value+'-use');await post('/evidence',{bindingId:w.bindingId,url:work.url,description:work.description||'已使用关键词 '+w.keyword},operationKey.value+'-work');notice.value='作品已提交，审核结果会显示在“审核进度”中。'}
 else if(action.value==='distribute')await post('/keywords/'+w.id+'/distribute',{targetId:target.value},operationKey.value)
 else await post('/bindings/'+w.bindingId+'/'+action.value,{executorId:target.value||undefined,reason:reason.value||undefined},operationKey.value)
 selected.value=null
}
onMounted(()=>run(async()=>{prices.value=(await props.context.http.get<{list:typeof prices.value}>('/price-agreements',{...props.context.scope,page:1,pageSize:100})).list}))
</script>
<template><section class="work-card"><div class="section-heading"><div><h2>{{admin?'关键词管理':context.role==='leader'?'团队关键词':'我的关键词'}}</h2><p>{{admin?'创建并分发关键词，按姓名查看使用情况。':context.role==='leader'?'领取后分发给团队成员，也可以自己使用。':'从这里提交作品，系统会自动记录关键词归属。'}}</p></div><button v-if="admin" class="primary" @click="createOpen=!createOpen">创建关键词</button></div>
<form v-if="createOpen&&admin" class="confirm-box" @submit.prevent="run(async()=>{await post('/keywords',form);createOpen=false;form.keyword='';notice='关键词已提交创建，成功后可分发。'})"><label>推广任务<select v-model="form.taskId" required><option v-for="t in context.options.tasks" :key="t.id" :value="t.id">{{t.name}}</option></select></label><label>渠道<select v-model="form.mappingId" required><option v-for="m in context.options.mappings" :key="m.id" :value="m.id">{{m.channelName}}</option></select></label><label>关键词<input v-model="form.keyword" required maxlength="128" /></label><label>推广内容链接<input v-model="form.landingUrl" type="url" required maxlength="1024" /></label><button class="primary" :disabled="busy">创建</button><button type="button" @click="createOpen=false">取消</button></form>
<form @submit.prevent="page=1;run(load)"><label>查找关键词<input v-model="search" placeholder="输入关键词" /></label><button :disabled="busy">搜索</button></form><p v-if="error" role="alert" class="engine-error">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
<div class="engine-table"><table><thead><tr><th>关键词 / 任务</th><th v-if="context.role!=='creator'">使用人</th><th v-else>适用单价</th><th>进度</th><th>操作</th></tr></thead><tbody><tr v-for="w in list" :key="w.id"><td>{{w.keyword}}<small>{{context.options.tasks.find(t=>t.id===w.taskId)?.name}}</small></td><td v-if="context.role!=='creator'">{{w.executorId?context.options.users.find(u=>u.id===w.executorId)?.displayName||'项目成员':w.leaderId?(context.options.users.find(u=>u.id===w.leaderId)?.displayName||'团长')+'待分发':'尚未分发'}}</td><td v-else>{{price(w)}}</td><td>{{status[w.lifecycleStatus]||'处理中'}}<small v-if="w.usedEverAt">{{w.verificationStatus==='passed'?'作品已通过':w.verificationStatus==='disputed'?'作品有争议':'等待作品审核'}}</small><small v-if="w.syncStatus==='failed'">创建未成功，请检查渠道和关键词</small></td><td><div class="engine-actions">
<button v-if="admin&&!w.bindingId&&w.lifecycleStatus==='available'" class="primary" :disabled="busy" @click="choose(w,'distribute')">分发给成员</button>
<button v-if="admin&&w.syncStatus==='failed'&&!w.usedEverAt" :disabled="busy" @click="run(()=>post('/keywords/'+w.id+'/retry-upstream'))">重新创建</button>
<button v-if="!admin&&!w.bindingId&&w.lifecycleStatus==='available'&&(context.role==='leader'||!context.parentId&&w.priorityEnded)" class="primary" :disabled="busy" @click="run(()=>post('/keywords/'+w.id+'/claim'))">领取关键词</button>
<button v-if="w.bindingId&&!w.usedEverAt&&w.leaderId&&(admin||w.leaderId===context.userId)" :disabled="busy" @click="choose(w,'assign')">分发给达人</button>
<button v-if="w.bindingId&&w.executorId===context.userId&&w.lifecycleStatus!=='retired'" class="primary" :disabled="busy" @click="choose(w,'work')">{{w.usedEverAt?'提交 / 补充作品':'提交作品并开始使用'}}</button>
<details v-if="w.bindingId"><summary>更多</summary><button v-if="!w.usedEverAt&&w.releaseStatus!=='requested'" :disabled="busy" @click="choose(w,'request-release')">退回未使用关键词</button><button v-if="admin&&w.releaseStatus==='requested'" :disabled="busy" @click="choose(w,'release')">审核退回</button><button v-if="w.usedEverAt&&w.lifecycleStatus!=='retired'" :disabled="busy" @click="choose(w,'stop')">停止使用</button></details>
</div></td></tr></tbody></table></div><p v-if="!list.length" class="empty-state">{{admin?'还没有关键词，请先创建。':context.role==='creator'?'暂时没有可用关键词，请联系团长或运营分配。':'暂时没有可领取或已分发的关键词。'}}</p>
<form v-if="selected" class="confirm-box" @submit.prevent="run(perform)"><h2>{{selected.keyword}}</h2><template v-if="action==='work'"><label>作品链接<input v-model="work.url" type="url" required maxlength="2048" /></label><label>补充说明（可选）<input v-model="work.description" maxlength="1000" /></label></template><label v-else-if="action==='assign'||action==='distribute'">分发给<select v-model="target" required><option value="">选择成员</option><option v-for="u in members" :key="u.id" :value="u.id">{{u.displayName}}（{{u.role==='leader'?'团长':'达人'}}）</option></select></label><template v-else><p>{{action==='stop'?'停止后保留历史归属和收入，请确认不再新增使用。':'未使用的关键词经运营审核后可以重新分发。'}}</p><label>原因<input v-model="reason" required maxlength="500" /></label></template><button class="primary" :disabled="busy">{{action==='work'?'提交作品':'确认'}}</button><button type="button" @click="selected=null">取消</button></form>
<div class="engine-actions" v-if="total>25"><button :disabled="page===1||busy" @click="page--;run(load)">上一页</button><span>第 {{page}} 页，共 {{total}} 条</span><button :disabled="page*25>=total||busy" @click="page++;run(load)">下一页</button></div>
</section></template>
