<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {errorText,requestKey,type EngineContext} from './context'
const props=defineProps<{context:EngineContext}>()
interface Work{id:string;bindingId:string;keyword:string;workUrl:string;description:string;status:string;verificationStatus:string;executorId:string;reason:string}
const list=ref<Work[]>([]),page=ref(1),total=ref(0),busy=ref(false),error=ref(''),notice=ref(''),selected=ref<Work|null>(null),reason=ref('')
const canReview=(w:Work)=>props.context.role==='admin'||props.context.role==='leader'&&w.executorId!==props.context.userId
async function load(){const r=await props.context.http.get<{list:Work[];total:number}>('/evidence',{...props.context.scope,page:page.value,pageSize:25});list.value=r.list;total.value=r.total}
async function review(w:Work,accept:boolean){busy.value=true;error.value='';try{await props.context.http.post('/evidence/'+w.id+'/review',{...props.context.scope,requestKey:requestKey(),accept,reason:accept?'已核对作品链接及关键词使用情况':reason.value});selected.value=null;notice.value=accept?'作品已通过审核，相关账单可以继续处理。':'已通知提交人修改作品。';await load()}catch(e){error.value=errorText(e)}finally{busy.value=false}}
async function refresh(){try{await load()}catch(e){error.value=errorText(e)}}
onMounted(refresh)
</script>
<template><section class="work-card"><div class="section-heading"><div><h2>{{context.role==='creator'?'作品审核进度':'作品审核'}}</h2><p>{{context.role==='creator'?'提交作品后，在这里查看结果。':'查看作品是否正确使用关键词，再决定是否通过。'}}</p></div><button :disabled="busy" @click="refresh">刷新</button></div><p v-if="error" role="alert" class="engine-error">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><div class="engine-table"><table><thead><tr><th>关键词</th><th v-if="context.role!=='creator'">提交人</th><th>作品</th><th>结果</th><th>操作</th></tr></thead><tbody><tr v-for="w in list" :key="w.id"><td>{{w.keyword}}</td><td v-if="context.role!=='creator'">{{context.options.users.find(u=>u.id===w.executorId)?.displayName||'项目成员'}}</td><td><a :href="w.workUrl" target="_blank" rel="noopener noreferrer">打开作品</a><p class="cell-note">{{w.description}}</p></td><td>{{w.status==='passed'?'已通过':w.status==='rejected'?'请修改后重新提交':'待审核'}}<p>{{w.reason}}</p></td><td><div v-if="w.status==='pending'&&canReview(w)" class="engine-actions"><button class="primary" :disabled="busy" @click="review(w,true)">审核通过</button><button :disabled="busy" @click="selected=w;reason=''">退回修改</button></div><span v-else>—</span></td></tr></tbody></table></div><p class="empty-state" v-if="!list.length">还没有提交的作品。</p><form v-if="selected" class="confirm-box" @submit.prevent="review(selected,false)"><h2>退回：{{selected.keyword}}</h2><label>需要修改什么<textarea v-model="reason" required maxlength="500" /></label><button :disabled="busy">确认退回</button><button type="button" @click="selected=null">取消</button></form><div class="engine-actions" v-if="total>25"><button :disabled="page===1||busy" @click="page--;refresh()">上一页</button><span>第 {{page}} 页，共 {{total}} 条</span><button :disabled="page*25>=total||busy" @click="page++;refresh()">下一页</button></div></section></template>

