import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, CircleDollarSign, Eye, MousePointer2, Plus, Target } from "lucide-react";
import { useMemo } from "react";
import { useLocation } from "wouter";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const number = new Intl.NumberFormat("zh-CN", { notation: "compact", maximumFractionDigits: 1 });
const money = new Intl.NumberFormat("zh-CN", { style: "currency", currency: "CNY", maximumFractionDigits: 0 });
const dateOffset = (days: number) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10);

export default function OverviewPage() {
  const [, setLocation] = useLocation();
  const overview = trpc.overview.useQuery();
  const trend = trpc.analytics.useQuery({ start: dateOffset(-6), end: dateOffset(0) });
  const data = overview.data;
  const rawTotals = data?.totals ?? { impressions: 0, clicks: 0, conversions: 0, spend: 0 };
  const totals = { impressions: Number(rawTotals.impressions) || 0, clicks: Number(rawTotals.clicks) || 0, conversions: Number(rawTotals.conversions) || 0, spend: Number(rawTotals.spend) || 0 };
  const ctr = totals.impressions ? ((totals.clicks / totals.impressions) * 100).toFixed(2) : "0.00";
  const cvr = totals.clicks ? ((totals.conversions / totals.clicks) * 100).toFixed(2) : "0.00";
  const chartData = useMemo(() => (trend.data ?? []).map(item => ({ ...item, label: item.metricDate.slice(5) })), [trend.data]);
  const hasSignal = Boolean(totals.impressions || totals.clicks || totals.conversions || totals.spend);
  const activeCampaigns = data?.campaigns.filter(item => item.status === "active").length ?? 0;

  return <div className="overview-journal">
    <section className="journal-intro"><div><p className="eyebrow">WEEKLY / OPERATION NOTE</p><h2>今天，先看清<br /><em>增长正在往哪里走。</em></h2><p>{new Date().toLocaleDateString("zh-CN", { month: "long", day: "numeric", weekday: "long" })}。OPC 已整理好本周的投放线索与待处理事项。</p></div><div className="journal-actions"><button className="primary-action" onClick={() => setLocation("/dashboard/campaigns")}><Plus size={16} />创建计划</button><button className="text-action" onClick={() => setLocation("/dashboard/analytics")}>查看分析 <ArrowRight size={16} /></button></div></section>
    <section className="focus-strip"><div><span>正在投放</span><strong>{activeCampaigns}</strong><small>个计划</small></div><p>账户状态稳定。<b>{activeCampaigns ? "继续关注转化效率。" : "从一条明确的计划开始。"}</b></p><button onClick={() => setLocation("/dashboard/campaigns")}>打开计划板 <ArrowRight size={15} /></button></section>
    <section className="metric-grid"><Metric label="曝光" value={number.format(totals.impressions)} note="本期累计" icon={Eye} tone="cyan" /><Metric label="点击" value={number.format(totals.clicks)} note={`点击率 ${ctr}%`} icon={MousePointer2} tone="indigo" /><Metric label="转化" value={number.format(totals.conversions)} note={`转化率 ${cvr}%`} icon={CheckCircle2} tone="mint" /><Metric label="消耗" value={money.format(totals.spend / 100)} note="本期累计" icon={CircleDollarSign} tone="violet" /></section>
    <section className="overview-main-grid"><article className="signal-paper"><header><div><p className="eyebrow">SEVEN-DAY SIGNAL</p><h3>一周投放信号</h3></div><span>{hasSignal ? "已同步" : "等待第一条数据"}</span></header>{hasSignal ? <div className="signal-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="opcSignal" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#214239" stopOpacity=".24" /><stop offset="100%" stopColor="#214239" stopOpacity="0" /></linearGradient></defs><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#7c877d", fontSize: 10 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#7c877d", fontSize: 10 }} width={30} /><Tooltip contentStyle={{ background: "#fffdf8", border: "1px solid #202923", borderRadius: 5, fontSize: 11 }} /><Area type="monotone" dataKey="impressions" name="曝光" stroke="#214239" strokeWidth={2.2} fill="url(#opcSignal)" /><Area type="monotone" dataKey="clicks" name="点击" stroke="#c96249" strokeWidth={1.8} fill="none" /></AreaChart></ResponsiveContainer></div> : <div className="signal-empty"><span>NO SIGNAL YET</span><strong>第一条计划，会从这里留下数据痕迹。</strong><p>创建并启动计划后，曝光、点击与转化趋势会按天沉淀。</p><button onClick={() => setLocation("/dashboard/campaigns")}>去创建计划 <ArrowRight size={15} /></button></div>}</article><article className="next-actions"><p className="eyebrow">NEXT / ACTIONS</p><h3>下一步，做什么？</h3><div className="action-item"><span>01</span><div><strong>{activeCampaigns ? "检查投放中的计划" : "建立第一条推广计划"}</strong><p>{activeCampaigns ? "确认预算和关键词是否仍然匹配当前目标。" : "用一个关键词、渠道和日预算开始。"}</p></div></div><div className="action-item"><span>02</span><div><strong>完成词条与回传</strong><p>让内容、投放和转化在同一条链路中发生。</p></div></div><button onClick={() => setLocation("/dashboard/keywords")}>前往配置 <ArrowRight size={15} /></button></article></section>
    <section className="overview-bottom-grid"><article className="panel activity-panel"><PanelTitle kicker="RECENT CAMPAIGNS" title="近期推广计划" link="全部计划" onLink={() => setLocation("/dashboard/campaigns")} />{data?.campaigns.length ? <div className="table-list">{data.campaigns.slice(0, 4).map((item, index) => <div className="campaign-row" key={item.id}><span className="list-index">{String(index + 1).padStart(2, "0")}</span><div><strong>{item.keyword}</strong><small>{item.channel}</small></div><div className="budget"><small>日预算</small><strong>{money.format(item.dailyBudget / 100)}</strong></div><span className={`status-badge ${item.status}`}>{({ active: "投放中", paused: "已暂停", draft: "草稿", ended: "已结束" } as Record<string, string>)[item.status]}</span></div>)}</div> : <Empty caption="目前还没有推广计划。" />}</article><article className="panel activity-panel"><PanelTitle kicker="CONVERSION LOG" title="最新回传日志" link="回传配置" onLink={() => setLocation("/dashboard/keywords")} />{data?.logs.length ? <div className="table-list">{data.logs.slice(0, 4).map(item => <div className="log-row" key={item.id}><span className={`log-icon ${item.status}`}>{item.status === "success" ? "✓" : item.status === "failed" ? "!" : "·"}</span><div><strong>{item.message}</strong><small>{item.context || item.type}</small></div><span className={`event-state ${item.status}`}>{item.status === "success" ? "已完成" : item.status === "failed" ? "待处理" : "等待中"}</span></div>)}</div> : <Empty caption="回传记录会在有转化时自动出现。" />}</article></section>
  </div>;
}

function Metric({ label, value, note, icon: Icon, tone }: { label: string; value: string; note: string; icon: React.ElementType; tone: string }) { return <article className="metric-card"><div><span>{label}</span><i className={`metric-icon ${tone}`}><Icon size={17} /></i></div><strong>{value}</strong><p>{note}</p></article>; }
function PanelTitle({ kicker, title, link, onLink }: { kicker: string; title: string; link?: string; onLink?: () => void }) { return <header className="panel-title"><div><p>{kicker}</p><h2>{title}</h2></div>{link && <button onClick={onLink}>{link} <ArrowRight size={13} /></button>}</header>; }
function Empty({ caption }: { caption: string }) { return <div className="empty-panel"><Target size={18} /><span>{caption}</span></div>; }
