const test=require('node:test')
const assert=require('node:assert/strict')
const d=require('../cloudfunctions/opc-api/lib/domain')
const {fixture,scope,identity}=require('./cloud-fixture.cjs')
test('cloud login binds session to trusted OpenID; token expires and account revocation works',async()=>{
  const f=await fixture(),token=await f.login('creator')
  assert.equal((await f.call(token,'GET','/core/auth/me')).data.role,'creator')
  assert.equal((await f.call(token,'GET','/core/auth/me',{}, {...identity,openid:'other'})).statusCode,401)
  const user=await f.store.get('users','3');await f.store.put('users','3',{...user,sessionVersion:1})
  assert.equal((await f.call(token,'GET','/core/auth/me')).statusCode,401)
})
test('client event cannot forge app identity, role or user; finance/operations duties remain separate',async()=>{
  const f=await fixture()
  const creator=await f.login('creator'),finance=await f.login('finance'),operations=await f.login('operations')
  assert.equal((await f.call(creator,'POST','/core/projects',{name:'x',slug:'x',role:'admin'})).statusCode,403)
  assert.equal((await f.call(finance,'GET','/modules/zhihu/keywords',scope)).statusCode,403)
  assert.equal((await f.call(operations,'GET','/core/finance',{...scope,moduleId:'zhihu'})).statusCode,403)
  assert.equal((await f.api.handle({method:'GET',path:'/core/auth/me',token:creator,openid:identity.openid},{})).statusCode,403)
})
test('scope authorization denies cross-project calls and writes after membership is removed',async()=>{
  const f=await fixture(),token=await f.login('creator')
  assert.equal((await f.call(token,'GET','/modules/zhihu/keywords',{...scope,projectId:'999'})).statusCode,403)
  await f.store.remove('members',d.hash(['1','3']))
  assert.equal((await f.call(token,'GET','/modules/zhihu/evidence',scope)).statusCode,403)
})
test('atomic keyword claim has one winner and retry with same key returns same binding',async()=>{
  const f=await fixture(),leader=await f.login('leader'),admin=await f.login('admin')
  const created=await f.call(admin,'POST','/modules/zhihu/keywords',{...scope,keyword:'cloud-keyword',taskId:'20',mappingId:'40',landingUrl:'https://www.zhihu.com/a',popularizeType:0,requestKey:'keyword-create-001'})
  assert.equal(created.code,0,created.message)
  const id=created.data.id,word=await f.store.get('keywords',id)
  await f.store.put('keywords',id,{...word,lifecycleStatus:'available',syncStatus:'synced',planStatus:'active'})
  const results=await Promise.all(['claim-key-001','claim-key-002'].map(requestKey=>f.call(leader,'POST','/modules/zhihu/keywords/'+id+'/claim',{...scope,requestKey})))
  assert.equal(results.filter(r=>r.code===0).length,1);assert.equal(f.dump('bindings').length,1)
  const retry=await f.call(leader,'POST','/modules/zhihu/keywords/'+id+'/claim',{...scope,requestKey:'claim-key-001'})
  assert.equal(retry.data.id,results[0].data.id)
})
test('full cloud business lifecycle: assign, activate, evidence review and retry',async()=>{
  const f=await fixture(),leader=await f.login('leader'),creator=await f.login('creator')
  await f.store.put('keywords','50',{id:'50',...scope,taskId:'20',mappingId:'40',keyword:'word',bindingId:'60',lifecycleStatus:'reserved'})
  await f.store.put('bindings','60',{id:'60',keywordId:'50',leaderId:'2',executorId:null,verificationStatus:'pending',releaseStatus:'none'})
  let result=await f.call(leader,'POST','/modules/zhihu/bindings/60/assign',{...scope,executorId:'3',requestKey:'assign-request-001'});assert.equal(result.code,0,result.message)
  result=await f.call(creator,'POST','/modules/zhihu/bindings/60/activate',{...scope,requestKey:'activate-request-001'});assert.equal(result.code,0,result.message)
  const input={...scope,bindingId:'60',url:'https://www.zhihu.com/question/1',description:'作品说明',requestKey:'evidence-request-001'}
  result=await f.call(creator,'POST','/modules/zhihu/evidence',input);assert.equal(result.code,0,result.message)
  const replay=await f.call(creator,'POST','/modules/zhihu/evidence',input);assert.equal(replay.data.id,result.data.id);assert.equal(f.dump('evidence').length,1)
  const review=await f.call(leader,'POST','/modules/zhihu/evidence/'+result.data.id+'/review',{...scope,accept:true,reason:'核对通过',requestKey:'review-request-001'});assert.equal(review.code,0,review.message)
  assert.equal((await f.store.get('bindings','60')).verificationStatus,'passed')
})
test('cloud price publication prevents leader payment exceeding platform price',async()=>{
  const f=await fixture(),leader=await f.login('leader')
  const price=await f.call(leader,'POST','/modules/zhihu/price-agreements',{...scope,taskId:'20',payeeId:'3',unitPrice:'2',from:'2026-01-01',reason:'test',requestKey:'draft-price-001'})
  assert.equal(price.code,0,price.message)
  const published=await f.call(leader,'POST','/modules/zhihu/price-versions/'+price.data.id+'/publish',{...scope,requestKey:'publish-price-001'})
  assert.equal(published.statusCode,409);assert.equal((await f.store.get('prices',price.data.id)).priceStatus,'draft')
})
async function fundFixture(f){
  await f.store.put('bindings','60',{id:'60',keywordId:'50',leaderId:'2',executorId:'3',verificationStatus:'passed',usedAt:d.now()})
  await f.store.put('facts','fact',{id:'fact',...scope,date:'2026-09-01',keyword:'word',bindingId:'60',orders:'1',version:'v1',allocations:[{userId:'3',amount:'10.0000'}],error:null,pendingRevision:null})
}
test('finance confirmation, release and concurrent withdrawals cannot overspend',async()=>{
  const f=await fixture();await fundFixture(f)
  const admin=await f.login('admin'),creator=await f.login('creator'),period={...scope,from:'2026-09-01',to:'2026-09-16'}
  const report=await f.call(admin,'GET','/modules/zhihu/workbench',period);assert.equal(report.code,0,report.message)
  let result=await f.call(admin,'POST','/modules/zhihu/workbench/confirm',{...period,reviewHash:report.data.reviewHash,acknowledged:true,requestKey:'confirm-bills-001'});assert.equal(result.code,0,result.message)
  let finance=await f.call(admin,'GET','/core/finance',{...scope,moduleId:'zhihu'})
  result=await f.call(admin,'POST','/core/finance/funding',{...scope,moduleId:'zhihu',hash:finance.data.funding.hash,reference:'bank-received'});assert.equal(result.code,0,result.message)
  const body={...scope,moduleId:'zhihu',amount:'8.00',receiverName:'A',bankName:'B',bankAccount:'C'}
  const responses=await Promise.all(['withdraw-001','withdraw-002'].map(requestKey=>f.call(creator,'POST','/core/finance/withdrawals',{...body,requestKey})))
  assert.equal(responses.filter(r=>r.code===0).length,1);assert.equal(f.dump('withdrawals').length,1)
  const retry=await f.call(creator,'POST','/core/finance/withdrawals',{...body,requestKey:'withdraw-001'});assert.equal(retry.code,0)
  finance=await f.call(creator,'GET','/core/finance',{...scope,moduleId:'zhihu'});assert.equal(finance.data.balance.available,'2.0000')
})
test('pending report correction blocks funded income and prevents withdrawal approval',async()=>{
  const f=await fixture();await fundFixture(f)
  await f.store.put('income',d.hash(['fact','3']),{id:d.hash(['fact','3']),...scope,userId:'3',factId:'fact',version:'v1',amount:'10.0000',availability:'available'})
  await f.store.put('withdrawals','80',{id:'80',...scope,userId:'3',amount:'10.0000',status:'pending',createdAt:d.now()})
  const fact=await f.store.get('facts','fact');await f.store.put('facts','fact',{...fact,pendingRevision:'revision'})
  const token=await f.login('admin'),result=await f.call(token,'POST','/core/finance/withdrawals/80/review',{...scope,action:'approve'})
  assert.equal(result.statusCode,409)
})
test('cloud request idempotency rejects payload changes and transaction failures roll back',async()=>{
  const f=await fixture(),user=await f.store.get('users','1')
  const result=await f.store.mutate(user,scope,'test','request-key-001',{n:1},tx=>tx.put('tasks','99',{id:'99'}))
  assert.equal(result.id,'99')
  await assert.rejects(f.store.mutate(user,scope,'test','request-key-001',{n:2},()=>null),/不同内容/)
  await assert.rejects(f.store.transaction(async tx=>{await tx.put('tasks','100',{id:'100'});throw Error('rollback')}))
  assert.equal(await f.store.get('tasks','100'),null)
})
test('timer worker marks uncertain upstream writes for reconciliation without retry',async()=>{
  const f=await fixture(),{run}=require('../cloudfunctions/opc-api/lib/worker')
  await f.store.put('keywords','50',{id:'50',...scope,syncStatus:'local'})
  await f.store.put('jobs','job',{id:'job',scope,type:'push-plan',keywordId:'50',status:'pending',nextAt:0,attempts:0,payload:{}})
  let calls=0;const upstream={request:async()=>{calls++;throw Error('timeout')}}
  await run(f.store,upstream);await run(f.store,upstream)
  assert.equal(calls,1);assert.equal((await f.store.get('jobs','job')).status,'uncertain')
})
