const test=require('node:test'),assert=require('node:assert/strict')
const {fixture,scope}=require('./cloud-fixture.cjs'),d=require('../cloudfunctions/opc-api/lib/domain')
test('historical withdrawals preserve cents, reserve atomically and retain two-stage review',async()=>{
 const f=await fixture(),creator=await f.login('creator'),leader=await f.login('leader'),admin=await f.login('admin')
 await f.store.put('legacy_earnings','1',{id:'1',userId:'3',projectId:'1',amount:'10000.0000',status:'confirmed'})
 const data={amount:'8000',settleType:'personal',payMethod:'wechat',payAccount:'test'}
 const responses=await Promise.all(['legacy-withdraw-001','legacy-withdraw-002'].map(requestKey=>f.call(creator,'POST','/modules/zhihu/withdrawals',{...data,requestKey})))
 assert.equal(responses.filter(r=>r.code===0).length,1);const id=responses[0].data.id
 assert.equal((await f.store.get('legacy_withdrawals',id)).amountYuan,'80.0000')
 assert.equal((await f.call(admin,'POST','/modules/zhihu/withdrawals/'+id+'/decide',{action:'approve',requestKey:'legacy-decide-001'})).statusCode,409)
 assert.equal((await f.call(leader,'POST','/modules/zhihu/withdrawals/'+id+'/review',{action:'approve',requestKey:'legacy-review-001'})).code,0)
 assert.equal((await f.call(admin,'POST','/modules/zhihu/withdrawals/'+id+'/decide',{action:'approve',requestKey:'legacy-decide-002'})).code,0)
 assert.equal((await f.store.get('legacy_withdrawals',id)).status,'approved')
 assert.equal((await f.call(creator,'POST','/modules/zhihu/withdrawals',{...data,requestKey:'legacy-withdraw-001'})).data.id,id)
})
test('appeal adjustment cannot cross the engine cutover or mint duplicate earnings',async()=>{
 const f=await fixture(),admin=await f.login('admin')
 await f.store.put('legacy_appeals','1',{id:'1',userId:'3',status:'leader_approved',kind:'补款'})
 const body={action:'approve',adjustAmount:1000,requestKey:'legacy-appeal-001'}
 assert.equal((await f.call(admin,'POST','/modules/zhihu/appeals/1/decide',body)).statusCode,409)
 assert.equal(f.dump('legacy_earnings').length,0)
 await f.store.remove('routes',d.hash(scope));await f.store.put('projects','1',{id:'1',slug:'zhihu',isEnabled:true})
 assert.equal((await f.call(admin,'POST','/modules/zhihu/appeals/1/decide',body)).code,0)
 assert.equal((await f.call(admin,'POST','/modules/zhihu/appeals/1/decide',body)).code,0)
 assert.equal(f.dump('legacy_earnings').length,1);assert.equal(f.dump('legacy_earnings')[0].amountYuan,'10.0000')
})
test('financial duty and historical row ownership cannot be forged',async()=>{
 const f=await fixture(),creator=await f.login('creator'),operations=await f.login('operations')
 await f.store.put('legacy_withdrawals','1',{id:'1',userId:'2',amount:'100',status:'pending'})
 assert.equal((await f.call(creator,'GET','/modules/zhihu/withdrawals')).data.total,0)
 assert.equal((await f.call(creator,'GET','/modules/zhihu/withdrawals/1/statement')).statusCode,403)
 assert.equal((await f.call(operations,'GET','/modules/zhihu/earnings')).statusCode,403)
})
test('dispute resolution invalidates prior financial review and creator trace hides other payouts',async()=>{
 const f=await fixture(),creator=await f.login('creator'),admin=await f.login('admin')
 await f.store.put('keywords','50',{id:'50',...scope,bindingId:'60'})
 await f.store.put('bindings','60',{id:'60',keywordId:'50',leaderId:'2',executorId:'3',verificationStatus:'passed'})
 await f.store.put('facts','fact',{id:'fact',...scope,date:'2026-09-01',version:'v1',bindingId:'60',allocations:[{userId:'2',amount:'1'},{userId:'3',amount:'2'}],priceIds:['private']})
 const trace=await f.call(creator,'GET','/modules/zhihu/attributions/fact/trace',scope)
 assert.equal(trace.code,0);assert.equal(trace.data.fact.allocations.length,1);assert.equal(trace.data.fact.priceIds,undefined)
 const result=await f.call(creator,'POST','/modules/zhihu/evidence-bindings/60/dispute',{...scope,resolve:false,reason:'attribution incorrect',requestKey:'dispute-open-001'})
 assert.equal(result.code,0);assert.notEqual((await f.store.get('facts','fact')).version,'v1')
 assert.equal((await f.call(creator,'POST','/modules/zhihu/evidence-bindings/60/dispute',{...scope,resolve:true,reason:'fixed',requestKey:'dispute-resolve-001'})).statusCode,403)
 assert.equal((await f.call(admin,'POST','/modules/zhihu/evidence-bindings/60/dispute',{...scope,resolve:true,reason:'fixed',requestKey:'dispute-resolve-002'})).code,0)
})
