const test=require('node:test'),assert=require('node:assert/strict')
const {memory}=require('./cloud-memory.cjs'),{collections}=require('../cloudfunctions/opc-api/lib/store')
const {isolatedStore,cleanup}=require('../cloudfunctions/opc-api/lib/acceptance-store')
test('acceptance database isolates document IDs, transactions, queries and cleanup from business rows',async()=>{
  const f=memory(),store=isolatedStore(f.db,'a'.repeat(24))
  await f.store.put('users','1',{id:'1',username:'real'})
  await store.put('users','1',{id:'1',username:'synthetic'})
  assert.equal((await f.store.get('users','1')).username,'real')
  assert.equal((await store.get('users','1')).username,'synthetic')
  assert.equal(f.dump('users').length,1)
  assert.deepEqual((await store.transaction(tx=>tx.find('users'))).map(row=>row.username),['synthetic'])
  await cleanup(store)
  assert.equal((await f.store.get('users','1')).username,'real')
  for(const name of collections)assert.equal(f.dump(name).filter(row=>row._qaRun).length,0)
})
test('server business acceptance completes all stages using real handlers and removes every synthetic record',async()=>{
  const f=memory(),{run}=require('../cloudfunctions/opc-api/lib/business-acceptance')
  await f.store.put('users','1',{id:'1',username:'untouched'})
  let result
  for(let i=0;i<6;i++){result=await run(f.store,f.db,{});if(['passed','failed'].includes(result.status))break}
  assert.equal(result.status,'passed',JSON.stringify(result))
  assert.deepEqual(result.checks,{seed:true,roles:true,operations:true,finance:true,cleanup:true})
  assert.equal((await f.store.get('users','1')).username,'untouched')
  for(const name of collections)assert.equal(f.dump(name).filter(row=>row._qaRun).length,0,name)
  assert.equal((await run(f.store,f.db,{})).status,'passed')
})
test('failed business acceptance returns a resumable cleanup stage and retains real rows',async()=>{
  const f=memory(),{run}=require('../cloudfunctions/opc-api/lib/business-acceptance')
  await f.store.put('users','1',{id:'1',username:'real'})
  await run(f.store,f.db,{})
  const state=await f.store.get('settings','business-acceptance'),store=isolatedStore(f.db,state.runId)
  const user=await store.get('users','1');await store.put('users','1',{...user,isActive:false})
  const failure=await run(f.store,f.db,{})
  assert.equal(failure.status,'cleaning');assert.equal(failure.stage,'cleanup')
  const final=await run(f.store,f.db,{})
  assert.equal(final.status,'failed');assert.equal(final.checks.cleanup,true)
  assert.equal((await f.store.get('users','1')).username,'real')
  assert.equal(f.dump('settings').filter(row=>row._qaRun).length,0)
})
