const test=require('node:test'),assert=require('node:assert/strict');const {harness,scoped}=require('./harness.cjs');
async function open(user={id:'1',role:'admin',adminDuty:'finance'}){const h=harness(c=>{const common=scoped(c);if(common!==undefined)return common;if(c.path==='/core/finance/workspace/entries')return {list:[{id:'1:3',taskName:'拉活词',metricLabel:'拉活',quantityUnit:'个',quantity:'5',unitPrice:'1.2345',amount:'6.1725'}],total:26,amount:'40.0100'};if(c.path==='/core/earnings/mine')return {list:[{id:'1',metricType:'activation',quantity:'5',amount:'6',isReady:1}],total:1,summary:{confirmedAmount:'4',pendingAmount:'2'}};if(c.path==='/core/finance')return {canManage:user.role==='admin',funding:{amount:'10.0000',hash:'checked-funding-hash'}};return {}});h.session(user);const page=h.page('wallet');await page.onShow();assert.equal(page.data.error,'');return {h,page};}
test('wallet reads full confirmed totals, type detail and server pagination',async()=>{const {h,page}=await open();assert.equal(page.data.report.summary.confirmed,'40.01');assert.equal(page.data.visibleEntries[0].priceText,'¥1.2345');await page.next();assert.equal(h.calls.findLast(c=>c.path.endsWith('/entries')).data.page,2);assert.equal(typeof page.confirmBills,'undefined');assert(!h.calls.some(c=>c.path==='/modules/zhihu/workbench'));});
test('member wallet uses own platform earnings and has no financial workspace request',async()=>{const {h,page}=await open({id:'3',role:'creator'});assert.equal(page.data.report.summary.confirmed,'4.00');assert.equal(page.data.report.summary.pending,'2.00');assert(!h.calls.some(c=>c.path.includes('/workspace/')));});
test('funding retains quote, acknowledgment and receipt reference',async()=>{const {h,page}=await open();page.setData({reference:'receipt'});await page.releaseFunding();assert.equal(h.calls.filter(c=>c.method==='POST').length,0);page.setData({fundingAcknowledged:true});await page.releaseFunding();const post=h.calls.find(c=>c.method==='POST');assert.equal(post.path,'/core/finance/funding');assert.equal(post.data.hash,'checked-funding-hash');assert.equal(post.data.reference,'receipt');});
test('changing dates invalidates funding acknowledgment',async()=>{const {h,page}=await open();page.setData({reference:'receipt',fundingAcknowledged:true});await page.dateChange({currentTarget:{dataset:{name:'from'}},detail:{value:'2026-01-01'}});await page.releaseFunding();assert(!h.calls.some(c=>c.method==='POST'));});

test('report page reads both metric types, analysis and filtered problems without legacy uploads',async()=>{
 const h=harness(c=>scoped(c)??(c.path.endsWith('/analysis')?{steps:[{key:'read',title:'读取',summary:'已读取'}],conclusion:{title:'拉活',value:'5 个'}}:{list:[{id:'1',reportKind:'activation',status:'committed',jobStatus:'completed'}],total:1}));h.session({id:'1',role:'admin',adminDuty:'finance'});const p=h.page('reports');await p.onShow();assert.equal(p.data.list[0].typeText,'拉活');assert.equal(p.data.list[0].statusText,'处理完成');await p.inspect({currentTarget:{dataset:{id:'1'}}});assert.equal(p.data.detail.steps[0].summary,'已读取');await p.section({currentTarget:{dataset:{section:'exceptions'}}});assert.equal(h.calls.at(-1).data.status,'open');assert.equal(typeof p.uploadReport,'undefined');assert.equal(typeof p.resolve,'undefined');assert(!h.calls.some(c=>c.method==='POST'));
});

test('already read reports do not regress to waiting for a lagging job, but active failures remain visible',async()=>{
 const h=harness(c=>scoped(c)??{list:[{id:'1',status:'processed',jobStatus:'pending'},{id:'2',status:'processed',jobStatus:'failed'}],total:2});
 h.session({id:'1',role:'admin',adminDuty:'finance'});const p=h.page('reports');await p.onShow();
 assert.equal(p.data.list[0].statusText,'已读取');assert.equal(p.data.list[1].statusText,'处理失败');
});
