const test=require('node:test'),assert=require('node:assert/strict');
const {harness,scoped}=require('./harness.cjs');
const summary={registered:3,submitted:1,failed:1,pending:1};
const actor={id:'2',role:'leader'};
const item={id:'composition:3',compositionId:'3',keyword:'测试作品',executorName:'团队达人',createdAt:'2026-10-02T16:10:00.000Z',releaseTime:'2026-10-01T04:00:00.000Z',workUrl:'https://www.douyin.com/video/1234567890123456789',syncStatus:'failed',planSyncStatus:'synced',failureReason:'请修改链接',compositionType:2,compositionSubType:6,canEdit:true};
function setup(user=actor){const h=harness(c=>scoped(c)??(c.path.endsWith('/work-activity')?{summary,list:[{id:'3',name:'团队达人',...summary}],total:1}:c.path.endsWith('/work-detail')?item:{list:[item],total:1}));h.session(user);return h;}
test('business data entry is available for every role and leads to work counts',async()=>{for(const role of ['creator','leader','admin','developer','operator']){const h=setup({id:'2',role,adminDuty:'finance'}),p=h.page('zhihu');await p.onShow();assert.equal(p.data.items.find(x=>x.label==='数据').path,'/pages/work-data/index');const d=h.page('work-data');await d.onShow();assert.equal(d.data.summary.registered,3);assert.equal(d.data.views.length,role==='creator'?1:2);}});
test('member and status drilldowns preserve registration dates, role view and canonical registered-only filter',async()=>{const h=setup(),p=h.page('work-data');await p.onShow();await p.changeView({currentTarget:{dataset:{view:'team'}}});p.works({currentTarget:{dataset:{id:'3',name:'团队达人'}}});const url=new URL(h.navigation.at(-1),'https://example.com');assert.equal(url.pathname,'/pages/works/index');assert.equal(url.searchParams.get('view'),'team');assert.equal(url.searchParams.get('ownerId'),'3');assert.equal(url.searchParams.get('registeredOnly'),'1');assert.equal(url.searchParams.get('from'),p.data.from);p.works({currentTarget:{dataset:{result:'failed'}}});assert.match(h.navigation.at(-1),/result=failed/);const works=h.page('works');works.onLoad(Object.fromEntries(url.searchParams));await works.onShow();const q=h.calls.at(-1).data;assert.equal(q.ownerId,'3');assert.equal(q.from,p.data.from);assert.equal(q.registeredOnly,'1');});
test('inverted dates do not send a statistics request',async()=>{const h=setup(),p=h.page('work-data');await p.onShow();const count=h.calls.length;await p.dateChange({currentTarget:{dataset:{name:'from'}},detail:{value:'2999-12-31'}});assert.match(p.data.error,/开始日期/);assert.equal(h.calls.length,count);assert.equal(p.data.summary,null);});
test('work details show complete record and original link for all roles without editing for finance',async()=>{for(const user of [actor,{id:'3',role:'creator'},{id:'1',role:'admin',adminDuty:'finance'}]){const h=setup(user),p=h.page('works');await p.onShow();if(user.adminDuty==='finance')assert.equal(p.data.list[0].canEdit,false);p.showDetail({currentTarget:{dataset:{id:item.id}}});assert.match(h.navigation.at(-1),/id=composition%3A3/);const detail=h.page('work-detail');detail.onLoad({id:item.id});await detail.onShow();assert.equal(detail.data.work.workUrl,item.workUrl);assert.equal(detail.data.work.createdText,'2026-10-03 00:10:00');assert.equal(detail.data.work.typeText,'视频');assert.equal(detail.data.work.subTypeText,'真人演绎');assert.equal(detail.data.work.upstreamReason,'请修改链接');}});
test('hidden detail and cleared sessions cannot use stale private content',async()=>{let resolve;const h=harness(c=>scoped(c)??new Promise(r=>resolve=r));h.session(actor);const p=h.page('work-detail');p.onLoad({id:item.id});const loading=p.onShow();while(!resolve)await new Promise(r=>setImmediate(r));p.onHide();resolve(item);await loading;assert.equal(p.data.work,null);assert.equal(p.canAct(),false);});

test('WeChat encoded route parameters decode once for member names and composition identifiers',async()=>{const h=setup(),p=h.page('works');p.onLoad({ownerName:encodeURIComponent('团队达人')});assert.equal(p.data.ownerName,'团队达人');const detail=h.page('work-detail');detail.onLoad({id:encodeURIComponent(item.id)});await detail.onShow();assert.equal(h.calls.at(-1).data.id,item.id);assert.equal(detail.data.work.workUrl,item.workUrl);});
