import type { ModuleManifest } from '../../core/contracts';
const creator = [
  'keyword.create',
  'keyword.read',
  'keyword.claim',
  'binding.use',
  'attribution.read',
  'evidence.submit',
  'statement.read',
  'composition.create',
  'composition.edit',
  'story.read',
  'earning.view_self',
  'withdraw.apply',
];
const leader = [
  ...creator,
  'catalog.sync',
  'plan.create',
  'plan.edit',
  'plan.delete',
  'keyword.bind',
  'earning.view_team',
  'withdraw.review',
  'binding.assign',
  'price.manage',
  'evidence.review',
  'statement.confirm',
];
export const zhihuManifest: ModuleManifest = {
  id: 'zhihu',
  name: '知乎',
  version: '1.0.0',
  contractVersion: 2,
  roles: ['developer', 'admin', 'operator', 'leader', 'creator'],
  entryPath: '/modules/zhihu',
  financeHistoryPath: '/modules/zhihu/earnings',
  accountCreation: 'managed',
  accountMessage: '当前使用迁移生成的历史接入账号；新增知乎凭证接入尚未开放。',
  capabilities: [
    'legacy-workflows',
    'email-import',
    'legacy-finance',
    'exclusive-attribution',
    'module-statements',
    'readonly-summary',
  ],
  permissions: {
    creator,
    leader,
    admin: [
      ...leader,
      'callback.config',
      'callback.secret',
      'earning.view_all',
      'withdraw.approve',
      'finance.relay',
      'data.import',
      'binding.release',
      'channel.manage',
      'attribution.manage',
      'engine.configure',
    ],
  },
};
