<script setup lang="ts">
import {computed} from 'vue'
import {useRoute} from 'vue-router'
import {useAuthStore} from '../../stores/auth'
import {modulePages} from './routes'
const route=useRoute(),auth=useAuthStore()
const daily=computed(()=>modulePages.filter(p=>{if(!p.meta?.section)return false;if(auth.user?.role!=='admin')return true;const duty=auth.user.adminDuty??'all';return duty==='finance'?p.meta.section==='finance':duty==='operations'?p.meta.section==='operations':p.meta.section!=='wallet'}))
const history=computed(()=>modulePages.filter(p=>!p.meta?.section&&p.path!=='keywords'))
</script>
<template><section class="page-stack"><nav class="module-toolbar" aria-label="知乎业务导航"><router-link v-for="p in daily" :key="p.path" :to="'/modules/zhihu/'+p.path">{{p.meta?.title}}</router-link><router-link class="back" to="/dashboard">OPC 工作台</router-link><details v-if="auth.user?.role==='admin'&&(auth.user.adminDuty??'all')==='all'"><summary>历史与维护</summary><div class="history-links"><p>旧流程资料保留。日常上传、收入与付款请使用新工作台。</p><router-link v-for="p in history" :key="p.path" :to="'/modules/zhihu/'+p.path">{{p.meta?.title}}</router-link></div></details></nav><p v-if="!route.meta.section&&!route.path.endsWith('/keywords')" class="history-note">当前为旧流程页面，日常业务请从上方工作台办理。</p><router-view /></section></template>
<style scoped>.module-toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap;padding:12px 16px;border:1px solid var(--line);border-radius:12px;background:var(--paper)}.module-toolbar>a{padding:8px 12px;border-radius:7px;font-size:14px;text-decoration:none}.module-toolbar .router-link-active{background:#195e62;color:white}.module-toolbar .back{margin-left:auto}.module-toolbar details{position:relative;font-size:12px}.module-toolbar summary{cursor:pointer}.history-links{position:absolute;right:0;top:28px;z-index:20;width:280px;max-height:400px;overflow:auto;box-shadow:0 8px 30px #0002;padding:18px;background:var(--paper);border:1px solid var(--line);border-radius:10px}.history-links a{display:block;padding:7px}.history-note,.history-links p{font-size:13px;color:var(--ink-soft)}</style>